### ISSUE TITLE
DataGrip Icon (a JetBrains product)

### ISSUE THREAD

**Issue by robfrawley** [numixproject/numix-icon-theme-circle#3301] opened 2016-07-21 07:45 UTC
Icon is missing for DataGrip, a JetBrains IDE that is part of their suite of products that also includes [PHPStorm](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/phpstorm.svg), [CLion](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/clion.svg), [RubyMine](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/rubymine.svg), and others.

*Note: Unfortunately, as is the case for all of the JetBrains' products, the `Icon` path in their default `.desktop` file is hard-coded. As such, I've added icon information instead following the naming conventions already used for the JetBrains products you currently support.*

Icon Info:

```
Name=DataGrip
Icon=datagrip
```

Original Icon:
![product](https://cloud.githubusercontent.com/assets/3967713/17014952/65d39f32-4ef5-11e6-9011-933076768edd.png)

**Comment by palob** [comment] 2016-07-21 16:12
Actually we've already got this [icon](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/datagrip.svg).

Perhaps your Numix Circle installation isn't up to date?

In case you installed via PPA there's this issue unfortunately: #2430

**Comment by Foggalong** [comment] 2016-08-01 17:16
Duplicate of #2722

**Closed by Foggalong** 2016-08-01 17:16 UTC
