### ISSUE TITLE
Icon google-chrome size 24x24

### ISSUE THREAD

**Issue by region51** [numixproject/numix-icon-theme-circle#1637] opened 2015-03-02 19:26 UTC
Something is Not Right Here
![2015-03-02 22 10 25](https://cloud.githubusercontent.com/assets/10940138/6448296/fb092884-c129-11e4-850d-4ccd452b3c7b.png) ![2015-03-02 22 21 05](https://cloud.githubusercontent.com/assets/10940138/6448391/af938024-c12a-11e4-8171-0962438b8450.png)

**Comment by Foggalong** [comment] 2015-03-10 13:13
Duplicate of #928

**Closed** 2015-03-13 17:17 UTC
Labels: duplicate
