### ISSUE TITLE
Icon for CrashPlan

### ISSUE THREAD

**Issue by bbarton1169** [numixproject/numix-icon-theme-circle#2113] opened 2015-05-16 00:49 UTC
Icon for CrashPlan is missing.
The icon line is "/usr/local/crashplan/skin/icon_app_128x128.png" and the original icon is attached.
![crashplan](https://cloud.githubusercontent.com/assets/12466764/7663989/5843f286-fb3b-11e4-815e-3d264d727f4f.png)

**Comment by palob** [comment] 2015-05-16 09:20
Hi, could you please add the name of the .desktop file?

**Comment by bbarton1169** [comment] 2015-05-16 13:22
Attached are the contents of the .desktop file:

[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=CrashPlan
Categories=;
Comment=CrashPlan Desktop
Comment[en_CA]=CrashPlan Desktop
Exec=/usr/local/crashplan/bin/CrashPlanDesktop
Icon=/usr/local/crashplan/skin/icon_app_128x128.png
Hidden=false
Terminal=false
Type=Application
GenericName[en_CA]=

**Comment by palob** [comment] 2015-05-16 13:25
It's only the icon line that matters :) and the name of the file. So what's the name?

**Comment by bbarton1169** [comment] 2015-05-16 14:07
The name of the file the shortcut launches is "CrashPlanDesktop".  The icon shows "CrashPlan" for it's name.  The website for the app is <https://www.code42.com/crashplan/>.

Let me know if I can provide anything else.

**Comment by palob** [comment] 2015-05-16 14:16
So is the name of the file which contents you showed above *CrashPlanDesktop.desktop*?

**Comment by Foggalong** [comment] 2015-05-16 14:45
Duplicate of #735

**Closed by Foggalong** 2015-05-16 14:45 UTC

**Comment by palob** [comment] 2015-05-16 14:48
Alright, so the hardcode-fixer script has got a fix already.
