### ISSUE TITLE
Synaptic status icon

### ISSUE THREAD

**Issue by in-in** [numixproject/numix-icon-theme-circle#2362] opened 2015-06-28 13:23 UTC
Guys, please do something with Synaptic status icon.
For me it is difficult to understand which package installed, because it is a tiny green mark.
![numix](https://cloud.githubusercontent.com/assets/8797432/8396517/f31b39f2-1db1-11e5-8a57-b94930587f58.png)

**Comment by Foggalong** [comment] 2015-06-28 13:29
This is a base theme issue (not to do with Circle) and is a duplicate of [this issue](https://github.com/numixproject/numix-icon-theme/issues/562) there.

**Closed by Foggalong** 2015-06-28 13:29 UTC

**Comment by in-in** [comment] 2015-06-28 13:40
Sorry

**Comment by Foggalong** [comment] 2015-06-28 13:42
Not a problem! :)

**Comment by in-in** [comment] 2015-06-28 14:17
I duplicate this question because the search does not find #562 :confused: 
![selection_001](https://cloud.githubusercontent.com/assets/8797432/8396676/5a34cc42-1db8-11e5-8bd5-16f7802617bb.png)

**Comment by bil-elmoussaoui** [comment] 2015-06-28 14:18
Well, it's a Numix base issue and not a Numix circle one

**Comment by Foggalong** [comment] 2015-06-28 14:18
Yeah, it's because you were searching in the wrong repository :P [this is the one](https://github.com/numixproject/numix-icon-theme) where base issues are kept

**Comment by in-in** [comment] 2015-06-28 14:20
Sorry again. I delete it. You so fast :smile:
