### ISSUE TITLE
icon: zenmap

### ISSUE THREAD

**Issue by BlackBeemo** [numixproject/numix-icon-theme-circle#2691] opened 2015-11-19 15:13 UTC
This tool has two launchers, normal user and as root. both share same icon.

[Desktop Entry]
Encoding=UTF-8
Name=Zenmap
GenericName=GUI Port Scanner
TryExec=zenmap
Exec=zenmap %F
Terminal=false
Icon=/usr/share/zenmap/pixmaps/zenmap.png
Type=Application
Categories=Application;Network;Security;
Comment=A cross-platform GUI for the Nmap Security Scanner.

[Desktop Entry]
Encoding=UTF-8
Name=Zenmap (as root)
GenericName=GUI Port Scanner
TryExec=/usr/share/zenmap/su-to-zenmap.sh
Exec=/usr/share/zenmap/su-to-zenmap.sh %F
Terminal=false
Icon=/usr/share/zenmap/pixmaps/zenmap.png
Type=Application
Categories=Application;Network;Security;
Comment=A cross-platform GUI for the Nmap Security Scanner.

![seleccion_002](https://cloud.githubusercontent.com/assets/5465862/11274265/a994383a-8ecf-11e5-99c1-4d4d21585a93.png)

**Comment by Foggalong** [comment] 2015-11-19 15:54
Duplicate of #587

**Closed by Foggalong** 2015-11-19 15:54 UTC
