### ISSUE TITLE
Icon for Koala

### ISSUE THREAD

**Issue by admat81** [numixproject/numix-icon-theme-circle#1565] opened 2015-02-09 21:06 UTC
Koala is a GUI application for Less, Sass, Compass and CoffeeScript compilation (http://koala-app.com).

Icon=koala

![koala](https://cloud.githubusercontent.com/assets/10930077/6115706/e3a9ae1c-b0a7-11e4-99a8-e792ad99dd2f.png)

:)

**Comment by gregorydk** [comment] 2015-02-10 09:36
Duplicate of https://github.com/numixproject/numix-icon-theme-circle/issues/1492

**Closed** 2015-02-10 09:51 UTC
Labels: duplicate
