### ISSUE TITLE
Icon for R (programming language)

### ISSUE THREAD

**Issue by morealaz** [numixproject/numix-icon-theme-circle#2828] opened 2016-02-04 13:47 UTC
[Desktop Entry]
Name=R
GenericName=environment for statistical computing
Comment=language and environment for statistical computing and graphics
Exec=R
Icon=/usr/share/pixmaps/r.png
DocPath=/usr/lib/R/doc/html/index.html
StartupNotify=true
Terminal=true
Type=Application
Categories=Science;

![r_logo svg](https://cloud.githubusercontent.com/assets/2796369/12816693/1aa57a96-cb63-11e5-8744-36898e59cf30.png)

**Comment by Foggalong** [comment] 2016-02-04 14:02
This icon is a hardcoded duplicate of #343. Please read the readme and open an issue at the repo linked

**Closed by Foggalong** 2016-02-04 14:02 UTC
Labels: hardcoded
