### ISSUE TITLE
Icon for xdiagnose

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-icon-theme-circle#2021] opened 2015-04-26 19:30 UTC
A numix-icon for xdiagnose is missing.
The icon line says "Icon=/usr/share/xdiagnose/icons/microscope.svg" and the original icon is attached.
![screenshot from 2015-04-26 21 29 07](https://cloud.githubusercontent.com/assets/11137173/7338901/74b225a8-ec5b-11e4-9ca8-6f6492c6da87.png)

**Comment by Foggalong** [comment] 2015-04-26 19:34
Duplicate of #90. We have one it's just hardcoded - see the readme for more details :)

**Closed by Foggalong** 2015-04-26 19:34 UTC
