### ISSUE TITLE
Icon for Teamviewer

### ISSUE THREAD

**Issue by LouisDK1** [numixproject/numix-icon-theme-circle#2163] opened 2015-05-21 08:26 UTC
I would be great with a Numix Circle themed icon for Teamviewer. This is the default icon:

![teamviewer](https://cloud.githubusercontent.com/assets/4969294/7744447/92428e9a-ffa3-11e4-9515-f93bcfb2d8be.png)

**Comment by Foggalong** [comment] 2015-05-21 11:08
Duplicate of #742

**Closed by Foggalong** 2015-05-21 11:08 UTC
Labels: duplicate

**Comment by LouisDK1** [comment] 2015-05-21 16:39
It difficult to search for a term when it's misspelled like "team viewer".

**Comment by Foggalong** [comment] 2015-05-21 17:29
[Nope](https://github.com/numixproject/numix-icon-theme-circle/issues?utf8=%E2%9C%93&q=Teamviewer+).
