### ISSUE TITLE
Icon for GpsPrune

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2402] opened 2015-07-12 12:24 UTC
Website: http://activityworkshop.net/software/gpsprune/

Icon=/usr/share/pixmaps/gpsprune.xpm

![gpsprune](https://cloud.githubusercontent.com/assets/7804464/8637730/8347954e-28a1-11e5-8f9b-cdc9d65c34b8.png)

**Comment by Foggalong** [comment] 2015-07-12 13:14
Hardcoded duplicate of #1977. Report this to tye hardcode fixer or manually change the icon line :)

**Closed by Foggalong** 2015-07-12 13:14 UTC

**Comment by gregorydk** [comment] 2015-07-12 13:39
Sorry, need to learn to check for duplicates.
