### ISSUE TITLE
Icon for Visual Studio Code

### ISSUE THREAD

**Issue by adriangaro** [numixproject/numix-icon-theme-circle#3004] opened 2016-04-20 22:18 UTC
It would be nice to have an icon for Visual Studio Code

Desktop file name: code.desktop

[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/bin/code %U
Icon=code
Type=Application
StartupNotify=true
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;

Default Icon:
![image](https://cloud.githubusercontent.com/assets/11583810/14692312/f7d4f982-075e-11e6-893b-d2c380d88150.png)

**Comment by Foggalong** [comment] 2016-04-20 22:23
Please read the README section on icon requests and add the information needed.

**Comment by adriangaro** [comment] 2016-04-21 17:34
I have updated the original comment, thanks for the help.

**Comment by Foggalong** [comment] 2016-04-21 20:15
Duplicate of #2964

**Closed by Foggalong** 2016-04-21 20:15 UTC
Labels: duplicate
