### ISSUE TITLE
Problem with Bluetooth icon in top panel in Gnome Classic on Ubuntu

### ISSUE THREAD

**Issue by pwittchen** [numixproject/numix-icon-theme-circle#2601] opened 2015-10-14 08:49 UTC
Hi.

First of all, I would like to thank you for providing great icons! I really like them and they're much better and cleaner than default system icons.

Right now, I have small problem with Bluetooth icon in top panel. It is cut and inconsistent with the rest of icons what doesn't look nice on my system. I understand your intentions and I see that icon is changing when we're turning Bluetooth on and off, but can we indicate this change in a different way, to keep consistent monochromatic style in top panel? E.g. we can have two different types of monochromatic Bluetooth icons. I have turned this icon off in control panel, because it destabilized my *feng shui*, but I would like to have it back in consistent style. :-)

My problem is visualized below.

![bluetooth-icon-in-top-panel](https://cloud.githubusercontent.com/assets/695319/10478799/56d045a2-7260-11e5-91e3-eb780ad557a4.png)

I've found out that icons I want to use are located in:
```
/usr/share/icons/Numix/scalable/status/bluetooth-active-symbolic.svg
/usr/share/icons/Numix/scalable/status/bluetooth-disabled-symbolic.svg
```

and they look OK and consistent with the rest of the top panel icons

How can I bring them back to the top panel?
Kind Regards,
Piotr

**Comment by pwittchen** [comment] 2015-10-14 09:03
I've found out that icons I want to use is located in:
```
/usr/share/icons/Numix/scalable/status/bluetooth-active-symbolic.svg
/usr/share/icons/Numix/scalable/status/bluetooth-disabled-symbolic.svg
```

and they look OK and consistent with the rest of the top panel icons

How can I bring them back to the top panel?

**Comment by dirtydancing** [comment] 2015-10-14 12:22
This arguably is a duplicate of https://github.com/numixproject/numix-icon-theme-circle/issues/2274.

@pwittchen I am not sure if things are different with GNOME Classic in Ubuntu, but usually for Ubuntu the icons you are referring to are located in the `panel` directories of Numix base and are named:

`bluetooth-active.svg`
`bluetooth-disabled.svg`

If they were the symbolic-named icons that you have listed, they should show up in the panel.

This is because an icon named

`bluetooth-active.svg`

is also located in Numix-Circle, apparently because another distro is using this icon name for other purposes than the panel (@foggalong ?). So removing/renaming `bluetooth-active.svg` in Numix-Circle should solve your issue.

@pwittchen Am I correct in assuming that the circle icon is only showing for active, and that a monochrome status icon is showing for inactive (Numix-Circle does not contain `bluetooth-disabled.svg`)? Things might be a little different again if your distro is using the `blueman` icons.

@wa4557 Can you possibly confirm this issue for Ubuntu?

**Comment by dirtydancing** [comment] 2015-10-14 12:36
Just to clarify: with Arch/GNOME (3.18), this issue does not exist. Screenshot:

![bluetooth](https://cloud.githubusercontent.com/assets/7164227/10483641/b6a4bce0-7280-11e5-83d3-4e5507b0d290.png)

**Comment by pwittchen** [comment] 2015-10-14 13:13
> @pwittchen Am I correct in assuming that the circle icon is only showing for active, and that a monochrome status icon is showing for inactive (Numix-Circle does not contain bluetooth-disabled.svg)? Things might be a little different again if your distro is using the blueman icons.

No. For Bluetooth Active it shows green Bluetooth icon like on the screen below.

![bluetooth-active](https://cloud.githubusercontent.com/assets/695319/10484306/baab75d2-7284-11e5-9b9b-49f3fe2e12b1.png)

For Bluetooth Inactive it shows blue Bluetooth icon like on the screen below.

![bluetooth-inactive](https://cloud.githubusercontent.com/assets/695319/10484327/d1f79fcc-7284-11e5-9e36-8a341cd270c7.png)

I'm using Ubuntu 14.04 LTS with Gnome Classic WM installed via `gnome-session-flashback`. If I'm correct it's also known as Gnome 2.

I've tried to delete the following icons from the `/usr/share/icons/Numix-Circle/scalable/apps` directory:
- `bluetooth.svg`
- `bluetooth-active.svg`

After that, question mark icon appeared in top panel instead of Bluetooth icon and Bluetooth icon disappeared form Control Panel (Settings) window.

On the screen below it looks fine, because I restored previous state, but after removing mentioned icons. Control panel has only Bluetooth text label without icon.

![control-panel](https://cloud.githubusercontent.com/assets/695319/10484547/e3b2b156-7285-11e5-84ac-490f6c709817.png)

It shows that top panel and Control panel are using the same Bluetooth icon. How can I set monochrome icon **only in top panel** without touching icon in Control Panel?

**Comment by dirtydancing** [comment] 2015-10-14 13:42
I see. 

The control panel seems to be using `bluetooth.svg`, so you can just leave that one in `/usr/share/icons/Numix-Circle/48x48/apps` (not in `scalable`, these are just symlinks with the target `48x48`).

The top panel (inactive blue) and the control panel (blue) may be using the same icon, but they might not be using the same icon name.

It makes sense that the green bluetooth icon is showing in the top panel for active, beacuse that is `bluetooth-active.svg`. 

It dos not make immediate sense that the blue bluetooth icon is showing in the top panel for inactive, because there is no `bluetooth-disabled.svg` in Numix-Circle.

Before we address the inactive blue bluetooth icon in your top panel, let's check the active green one. You write that a question mark appeared. This is probably an icon cache thing. After removing/renaming `bluetooth-active.svg` from Numix-Circle, please try an icon cace update via terminal:

`sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle`

and

`sudo gtk-update-icon-cache -f /usr/share/icons/Numix`

Is the monochrome `bluetooth-active.svg` showing in the panel now?

**Comment by pwittchen** [comment] 2015-10-14 13:47
I've executed these commands and nothing changed. Still Blue circle icon is showing for Bluetooth inactive and green circle icon is showing for Bluetooth active.

**Comment by dirtydancing** [comment] 2015-10-14 13:48
Well, did you remove/rename `bluetooth-active.svg` (green) from Numix-Circle?

**Comment by pwittchen** [comment] 2015-10-14 13:53
I didn't remove it in previous attempt

Now, I performed the following steps
- removed bluetooth-active.svg icon from `/usr/share/icons/Numix-Circle/48x48/apps`
- executed `sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle`
- executed `sudo gtk-update-icon-cache -f /usr/share/icons/Numix`

After that both for Bluetooth active and Bluetooth inactive blue circle Bluetooth icon is displayed. Green icon is not displayed anymore.

Unfortunately, I still don't have monochromatic Bluetooth icon.

**Comment by dirtydancing** [comment] 2015-10-14 14:00
Woah, this is quite strange!

One possible reason for this is that for both active and inactive in the panel, the icon lookup "falls back" to `bluetooth.svg` if there is no `bluetooth-active.svg` and no `blueetooth-disabled.svg` icon, and that the icon lookup looks into the `scalable` directory first and foremost. And because in Numix-Circle, the `scalable` directory is a symlink to `48x48`, the icon lookup in both cases finds the blue `bluetooth.svg` icon from `scalable` -> `48x48`.

Let's see: Could you please delete `bluetooth.svg` from Numix-Circle and again perform the icon cache update, and check if now the two different monochrome icons are showing in the panel? We can still get back in the next step to see how to deal with the control panel.

**Comment by pwittchen** [comment] 2015-10-14 14:08
Yeah! We're heading to the right direction!

Now, steps were as follows:

- I removed `bluetooth.svg` from directory `/usr/share/icons/Numix-Circle/scalable/apps`
- executed `sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle`
- executed `sudo gtk-update-icon-cache -f /usr/share/icons/Numix`

and now **top panel finally looks fine** for active and inactive Bluetooth and I can see monochromatic icons. Thank you for help. :-)

Now, I have another issue with control panel, which missed rounded Numix icon, which was there earlier.

![control-panel-2](https://cloud.githubusercontent.com/assets/695319/10486084/a0baae1e-728d-11e5-9b22-66c896d82516.png)

**Comment by dirtydancing** [comment] 2015-10-14 14:14
Haha, you already took the next step :) I thought you had removed `bluetooth.svg` from `48x48` in Numix-Circle, and was about to suggest to remove it only from `scalable` in Numix-Circle. But you have written that you removed `bluetooth.svg` from `scalable` in Numix-Circle.

OK then, I am glad to hear that the two monochrome bluetooth panel icons are working now! Unfortunately, at the moment I cannot think of a solution for the control panel. It appears that the control panel as well insists on `bluetooth.svg` from `scalable`, which is too bad, because in Numix-Circle there should still be `blueetoogh.svg` in `48x48`. Can you confirm that you have `bluetooth.svg` in `48x48` in Numix-Circle, and that it is still not showing in the control panel?

**Comment by pwittchen** [comment] 2015-10-14 14:19
I don't have `bluetooth.svg` in `/usr/share/icons/Numix-Circle/48x48/apps`. Probably I removed it during my previous attempts to fix the problem.

**Comment by dirtydancing** [comment] 2015-10-14 14:21
Ah OK. Can you put `bluetooth.svg` back into `/usr/share/icons/Numix-Circle/48x48/apps`. It might make sense to just rename the icons and not remove them, so that you are more flexible.

**Comment by dirtydancing** [comment] 2015-10-14 14:24
Just to clarify: `scalable/apps` is a folder symlink with the target `48x48/apps`, and I am not exactly sure how this effects this issue.

**Comment by pwittchen** [comment] 2015-10-14 15:30
Okay. Now, I removed Numix icons, installed them again and repeated steps from https://github.com/numixproject/numix-icon-theme-circle/issues/2601#issuecomment-148061435, but this time I renamed `bluetooth.svg` to `bluetooth-temp.svg`. You're right - `scalable/apps` is symlink to `/usr/share/icons/Numix-Circle/48x48/apps`, so in `/usr/share/icons/Numix-Circle/48x48/apps` i just have renamed `bluetooth-temp.svg` file and no `bluetooth.svg` file. Top panel icons are fine, but Control Panel icon is not fine. Situation is the same as I described in https://github.com/numixproject/numix-icon-theme-circle/issues/2601#issuecomment-148061435.

**Comment by dirtydancing** [comment] 2015-10-14 15:58
This is a new specific situation that I have not seen in any other distro so far. To me, this looks like an issue with Ubuntu/GNOME Classic, not like an issue with Numix.

The icon lookup is rather odd. E.g., for `bluetooth-active.svg`, the monochrome icons in Numix-Circle's `panel` directories 16x16/22x22/24x24 should be found once the green `bluetooth-active.svg` is removed/renamed in  the `apps` directory 48x48/scalabe. But apparently it is also necessary to remove/rename the blue `bluetooth.svg` in 48x48/scalable for the panel icons to be displayed properly.

This is at the cost of the control center icon, which looks like `bluetooth.svg` from `hicolor/scalable/apps` (fallback icon theme), and I am afraid this cannot be fixed from Numix's side.

What you could try, though, is to rename `bluetooth.svg` in `hicolor/scalabe/apps`, and then copy the blue Numix-Circle `bluetooth.svg` to `hicolor/scalable/apps`. This will be a matter of inheritances icon lookup, and it might be that the panel will stick with the monochrome icons, and that at the same time the control center will display the blue Numix-Circle bluetooth icon. Any luck with that approach?

**Comment by dirtydancing** [comment] 2015-10-14 16:27
Ah, you will probably also need to run another icon cache update for `hicolor`:

`sudo gtk-update-icon-cache -f /usr/share/icons/hicolor`

**Comment by pwittchen** [comment] 2015-10-14 16:38
I followed your instructions, but with no luck.

**Comment by dirtydancing** [comment] 2015-10-14 16:45
What happened? Is still the same non-Circle bluetooth icon showing in control center?

One alternative might be that specifically size 48x48 is used for control center. So you could try this: in `hicolor/48x48/apps`, rename `bluetooth.png` and copy Numix-Circle's blue `bluetooth.svg` there.

**Comment by pwittchen** [comment] 2015-10-14 17:19
> What happened? Is still the same non-Circle bluetooth icon showing in control center?

Yes.

> One alternative might be that specifically size 48x48 is used for control center. So you could try this: in hicolor/48x48/apps, rename bluetooth.png and copy Numix-Circle's blue bluetooth.svg there.

Great! That helped. Now I have what I wanted. Circle Bluetooth icon in Control Center and monochromatic icon for active/inactive state in top panel.

Thank you! :-D

I'd be great if these settings could be applied automatically during installation/update, but at least now we know, how to fix it manually.

**Comment by dirtydancing** [comment] 2015-10-14 17:44
Sweet! And yeah, you should consider this to be a quite individual manual workaround. Catering to this specific setup automatically would probably break all kinds of things in other distros/DEs.

**Comment by dirtydancing** [comment] 2015-10-14 17:55
@Foggalong In my view, this issue can be closed now. To me, this is a special case, and I would not recommend to e.g. remove `bluetooth.svg` from `48x48/apps`, as this would break many control panels, and it would arguably not be recommendable to start to place additional icons in `hicolor` automatically.

**Comment by dirtydancing** [comment] 2015-10-15 05:52
@pwittchen Wait, I have a question: Did this issue occur newly when you reported it, i.e. were the correct monochrome bluetooth panel icons displayed before?

I am asking because there could be another reason for this issue, and we might have worked around the wrong problem :)

**Comment by pwittchen** [comment] 2015-10-15 08:42
This issue occurred when I reported it. Earlier everything was fine and I had monochromatic icon in top panel and circle icon in Control Center. I suppose some recent update could broke it, but I don't know the root cause.

**Comment by wa4557** [comment] 2015-10-15 08:47
Are you using the version from PPA?

**Comment by pwittchen** [comment] 2015-10-15 08:48
Yes. I've installed icons in the following way:

```
sudo add-apt-repository ppa:numix/ppa
sudo apt-get update
sudo apt-get install numix-gtk-theme numix-icon-theme numix-icon-theme-circle
```

**Comment by dirtydancing** [comment] 2015-10-15 08:50
OK, let's see if we can trace this down. All of this is not reproducible on my machine, as I am on Arch/GNOME, and I am making use of the AUR Numix git packages.

The root cause might be that there is a wrong folder symlink in Numix-Circle, in the `panel` directories 16x16/22x22/24x24. The target folders in Numix base were renamed from 16x16/22x22/24x24 to 16/22/24.

Could you check e.g. the properties of `22x22/panel` in Numix-Circle: what is the target folder?

**Comment by pwittchen** [comment] 2015-10-15 09:02
Here's my terminal output
```
~ » cd /usr/share/icons/Numix-Circle/16x16 
Numix-Circle/16x16 » ls -la
razem 8
drwxr-xr-x 2 root root 4096 paź 14 17:22 .
drwxr-xr-x 7 root root 4096 paź 14 18:24 ..
lrwxrwxrwx 1 root root   23 lip 16 18:48 panel -> ../../Numix/16x16/panel
```

The same situation is in the following locations:
- `/usr/share/icons/Numix-Circle/16x16 -> ../../Numix/16x16/panel`
- `/usr/share/icons/Numix-Circle/22x22 -> ../../Numix/22x22/panel`
- `/usr/share/icons/Numix-Circle/24x24 -> ../../Numix/24x24/panel`

but there's no directories like `16x16`, `22x22` and `24x24` in `/usr/share/icons/Numix` and icon in the `Numix-Circle` directory shows that symlink is broken.

I think we're heading to root of this problem.

**Comment by dirtydancing** [comment] 2015-10-15 09:05
Indeed: with the current git versions, the target folder of e.g. `22x22/panel` is `../../Numix/22/panel`.

This has been corrected in Numix-Circle git already, but apparently has not landed in the PPA yet.

**Comment by pwittchen** [comment] 2015-10-15 09:08
Ok. Thank you for help and detailed information. I'll wait for the update on PPA. :-)

**Comment by dirtydancing** [comment] 2015-10-15 09:11
Yes, this appears to be the problem here. So then you can also revert your previous manual changes and things will work automatically.

But unfortunately, there is currently a problem with the Numix-Circle PPA updates, so this might be a little while, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/2430.

**Comment by wa4557** [comment] 2015-10-15 09:24
Try what I suggested here, then it should work again: #2602

**Comment by pwittchen** [comment] 2015-10-15 09:28
@wa4557 **It works with hacks and workarounds** described above :-). If am right it's okay on Git repository and will be released in the next update.

**Comment by wa4557** [comment] 2015-10-15 09:38
Fair enough :)

**Comment by wa4557** [comment] 2015-12-16 10:24
@Foggalong Can be closed :)

**Closed** 2015-12-16 11:51 UTC
Labels: bug

**Comment by pwittchen** [comment] 2015-12-18 18:35
Great! Thanks! :-)
