### ISSUE TITLE
Discord Canary icon is not present outside of the applications folder

### ISSUE THREAD

**Issue by Dizeeee** [numixproject/numix-icon-theme-circle#5] opened 2016-08-23 02:48 UTC
Here is the launcher info:

[Desktop Entry]
Name=Discord Canary
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/usr/share/discord-canary/DiscordCanary
Icon=discord-canary
Type=Application
StartupNotify=true
Categories=Network;InstantMessaging;

**Comment by palob** [comment] 2016-08-29 06:43
duplicate of #3.

**Comment by palob** [comment] 2016-08-30 20:32
@Dizee Fixed?

**Closed** 2016-09-08 23:23 UTC
Labels: duplicate
