### ISSUE TITLE
Gdebi has no circular icon

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2367] opened 2015-07-01 14:11 UTC
In gdebi.desktop: Icon=gnome-mime-application-x-deb

Can this be fixed?

**Comment by bil-elmoussaoui** [comment] 2015-07-01 14:19
Duplicate of #1452

**Comment by palob** [comment] 2015-07-01 14:20
The current icon line points to a mimetype icon name.

To fix it you have to change the icon line to ``Icon=gdebi`` manually or run the [hardcode fixer script](https://github.com/Foggalong/hardcode-fixer).

**Closed** 2015-07-01 17:46 UTC
Labels: duplicate
