### ISSUE TITLE
Icon for MultiWriter

### ISSUE THREAD

**Issue by JulienRbt** [numixproject/numix-icon-theme-circle#1796] opened 2015-03-28 20:45 UTC
Please for an icon for Gnome MultiWriter; MultiWriter is a iso usb *burner*.
[Website](https://wiki.gnome.org/Apps/MultiWriter)

Original icon:
![MultiWriter](https://wiki.gnome.org/Apps/MultiWriter?action=AttachFile&do=get&target=gnome-multi-writer.png)

/usr/share/applications/org.gnome.Multiwriter.desktop content:
Icon=gnome-multi-writer

**Comment by palob** [comment] 2015-03-28 21:48
Already present in Numix-Circle master.

**Comment by Foggalong** [comment] 2015-03-28 22:26
Duplicate of #1640. See [here](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gnome-multi-writer.svg) for the icon :)

**Closed by Foggalong** 2015-03-28 22:26 UTC

**Comment by bil-elmoussaoui** [comment] 2015-03-28 22:28
The icon have been added 25 days ago, the ppa should have been updated nop? (just wondering)

**Comment by Foggalong** [comment] 2015-03-28 22:30
Not gonna update the PPA until we've got the status icons as good as they can get :)
