### ISSUE TITLE
the numix cirvle icon theme have problems with librsvg  2.41.0.r11.g11d99a0-1

### ISSUE THREAD

**Issue by javashin** [numixproject/numix-icon-theme-circle#34] opened 2017-02-01 01:40 UTC
http://imgur.com/a/hq3rS
the icon looks like this in plank and the menu 
and without  librsvg  2.41.0.r11.g11d99a0-1
looks normal like this http://imgur.com/a/ZBOJZ

**Comment by palob** [comment] 2017-02-01 02:28
Looks like linear gradients don't work.

**Comment by Foggalong** [comment] 2017-02-02 23:12
huh, that's super weird. do we need to add a packaging dependency for librsvg or is this something we can fix some other way?

**Comment by palob** [comment] 2017-02-02 23:38
Well, 2.41 isn't a stable release and librsvg is amidst being rewritten in Rust. Afaik our gradients are valid SVG. @javashin Can you create a square with a linear gradient on it, save it as SVG and see check it looks?

**Comment by Foggalong** [comment] 2017-04-05 13:52
@javashin What OS is this with? I haven't been able to replicate this issue :/

**Comment by Foggalong** [comment] 2017-12-24 16:04
Closing this due to lack of updates, reproducibility, and likely coming down to using unstable libraries.

**Closed by Foggalong** 2017-12-24 16:04 UTC
Labels: bug
