### ISSUE TITLE
The generated cache was invalid.

### ISSUE THREAD

**Issue by xploshioOn** [numixproject/numix-icon-theme-circle#1772] opened 2015-03-22 00:36 UTC
Ive tried to install this with sudo apt-get install and installed all ok, but this message in the install
gtk-update-icon-cache: The generated cache was invalid.

even when i run it manually, is the same error

gtk-update-icon-cache -f /usr/share/icons/Numix-Circle
gtk-update-icon-cache: The generated cache was invalid.

the theme work correctly, but just to let you know

**Comment by Foggalong** [comment] 2015-03-22 01:46
Duplicate of #915. Fix is released, just needs to be pushed to the PPA :)

**Closed** 2015-03-22 01:46 UTC
Labels: duplicate
