### ISSUE TITLE
Icon for Vivaldi browser please

### ISSUE THREAD

**Issue by maxdraki** [numixproject/numix-icon-theme-circle#1814] opened 2015-04-01 06:52 UTC
Could we have an icon for the Vivaldi browser please
Icon=vivaldi
![image](https://cloud.githubusercontent.com/assets/3703338/6935899/fa261446-d843-11e4-8cce-e1994716224b.png)

**Comment by Foggalong** [comment] 2015-04-01 11:01
Duplicate of #1510 - we have one, its just not been released to the PPA yet

**Closed by Foggalong** 2015-04-01 11:01 UTC
Labels: duplicate
