### ISSUE TITLE
Small application icons are blurry

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-icon-theme-circle#2585] opened 2015-10-02 00:24 UTC
Numix icon theme is svg-based. Small application icons do not scale well, they become blurry

Example #1: a media player (Rhythmbox) icon on the 'Media Player indicator'
![screenshot from 2015-10-01 20-56-07](https://cloud.githubusercontent.com/assets/7532854/10236928/427737ce-6882-11e5-8dbc-f973de9f4c91.png)

Example #2: 'Drafts' icon in Evolution is the 'generic text editor' one
![screenshot from 2015-10-01 20-56-31](https://cloud.githubusercontent.com/assets/7532854/10236950/86c18c0e-6882-11e5-8d7e-cd38ad9c9d34.png)

**Comment by Foggalong** [comment] 2015-10-02 02:04
Happily, this is a duplicate of #2545! We're working on a possible solution at the moment but as you can imagine resizing 10,000+ icons is no easy task :)

**Closed by Foggalong** 2015-10-02 02:04 UTC
