### ISSUE TITLE
KDE Plasma 5 Invalid Panel Context

### ISSUE THREAD

**Issue by Kallestofeles** [numixproject/numix-icon-theme-circle#46] opened 2017-04-22 07:52 UTC
Hello,

With both numix-icon-theme and numix-icon-theme-circle installed, they work fine on Gnome3, XFCE, Mate, Openbox, etc. But when I set the theme to any of the Numix themes on KDE Plasma 5, then it works, but the terminal gets flooded with the following messages every time:
`Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/16/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/16@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/22/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/22@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/24/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/24@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/16/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/16@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/22/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/22@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/24/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/24@2x/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Numix/48/notifications/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Numix/48@2x/notifications/"`
Checked the folders and the correct icons seem to be in place.
Reinstalled Plasma desktop. Completely removed Numix themes and reinstalled them from AUR, but without success.
Other icon themes on the system seem to work just fine. Well, Numix works just fine as well, but just blasts out those warning messages every time a console is opened.
Is there a fix for this or does anyone know what might be causing it?

OS: Arch Linux
DE: KDE 5.33.0 / Plasma 5.9.4
WM: KWin
Icon Theme: Numix-Circle

If any info is needed, I'm more than happy to supply.

Best regards,
Kallestofeles

**Comment by palob** [comment] 2017-04-22 08:23
Duplicate of https://github.com/numixproject/numix-core/issues/3277.

**Closed by palob** 2017-04-22 08:23 UTC
