### ISSUE TITLE
Icon for Slack

### ISSUE THREAD

**Issue by Grifo07** [numixproject/numix-icon-theme-circle#3243] opened 2016-06-21 19:10 UTC
A numix-circle icon for Slack is missing.
The icon line says /usr/share/pixmaps/slack.png and the original icon is attached. Also the entry:

[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/bin/slack --disable-gpu %U
Icon=/usr/share/pixmaps/slack.png
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=x-scheme-handler/slack;

![slack](https://cloud.githubusercontent.com/assets/14910540/16242797/848005d2-37f4-11e6-8645-7633ad2f9441.png)

Thanks for the great work

**Comment by bil-elmoussaoui** [comment] 2016-06-21 19:11
Duplicate of #2542 #2566, the icon does not quite look like the original slack icon, but an issue is already open about that #2604

**Comment by Grifo07** [comment] 2016-06-21 19:13
ups, sorry!

**Comment by bil-elmoussaoui** [comment] 2016-06-21 19:14
@Grifo07 Not a problem, Can you close this? :)

**Comment by Grifo07** [comment] 2016-06-21 19:16
Yes, but the icon here it's the original. It's the Icon=/usr/share/pixmaps/slack.png file itself.

**Comment by bil-elmoussaoui** [comment] 2016-06-21 19:17
That's because the icon is hardcoded, take a look at https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons

**Closed** 2016-06-21 19:16 UTC

**Comment by Grifo07** [comment] 2016-06-21 19:20
Thanks
