### ISSUE TITLE
Icon for foxit reader

### ISSUE THREAD

**Issue by alkaef** [numixproject/numix-icon-theme-circle#2978] opened 2016-04-17 01:59 UTC
[Desktop Entry]
Name=Foxit Reader
Comment=View pdf documents
Keywords=pdf;octet-stream;
StartupNotify=true
Terminal=false
Type=Application
Categories=Application;Office;Viewer;X-Red-Hat-Base;
MimeType=application/pdf;application/octet-stream;
Icon=FoxitReader
Exec=/opt/foxitsoftware/foxitreader/FoxitReader.sh

**Default icon**
![foxitreader-128x128](https://cloud.githubusercontent.com/assets/13399275/14584639/3b0a4898-047a-11e6-9aa4-cae03c25c04a.png)

**Mine**
![fr](https://cloud.githubusercontent.com/assets/13399275/14584642/5844f868-047a-11e6-8926-45e350ab1b9d.png)

The thing is, the icon does change in the .desktop file, but not on unity launcher --the icon stay the same (default)

**Comment by bil-elmoussaoui** [comment] 2016-04-17 08:25
Duplicate of #2917 #2581 #2682

**Comment by Foggalong** [comment] 2016-04-17 08:39
It's only actually a duplicate of #2917 because that's the only one with the same icon name.

**Closed** 2016-04-17 08:38 UTC
Labels: duplicate
