### ISSUE TITLE
Icon Requests for a Few Useful Utilities and Semi-Popular Games...

### ISSUE THREAD

**Issue by bongochong** [numixproject/numix-icon-theme-circle#2826] opened 2016-02-03 22:39 UTC
I thought I'd put them all in one place, instead of making a ton of different requests and clogging up your issue tracker, any way, here are my requests:

- CryptoTE (https://panthema.net/2009/cryptote/)
![cryptote](https://cloud.githubusercontent.com/assets/10101120/12800023/9cebe956-ca8f-11e5-9129-0156f94a267a.png)
Icon=cryptote

- CPU-G (https://launchpad.net/cpug)
![cpug](https://cloud.githubusercontent.com/assets/10101120/12800025/9ceeb014-ca8f-11e5-845d-44850c9b987b.png)
Icon=/usr/share/pixmaps/cpu-g_128.png

- X Tile (http://www.giuspen.com/x-tile/)
![xtile](https://cloud.githubusercontent.com/assets/10101120/12800024/9cee2e46-ca8f-11e5-826e-17ad0be8d55b.png)
Icon=x-tile

- KKEdit (http://www.webupd8.org/2014/03/kkedit-text-editor-inspired-by-bbedit.html)
![kkedit](https://cloud.githubusercontent.com/assets/10101120/12800028/9d0368c4-ca8f-11e5-8ac9-00cc5f6e87ef.png)
Icon=KKEdit
Icon=KKEditRoot

- MultiSystem (http://liveusb.info/dotclear/)
![multisystem](https://cloud.githubusercontent.com/assets/10101120/12800033/9d162d6a-ca8f-11e5-9d15-6866a4937dfa.png)
Icon=multisystem-liveusb
Icon=multisystem-vbox

- ReNoise (https://www.renoise.com/)
![renoise](https://cloud.githubusercontent.com/assets/10101120/12800026/9cf0cc28-ca8f-11e5-89e2-827a0d846024.png)

- OGMRip (http://ogmrip.sourceforge.net/en/index.html)
![ogmrip](https://cloud.githubusercontent.com/assets/10101120/12800027/9cfb265a-ca8f-11e5-8131-2c705b0e8e85.png)
Icon=ogmrip

- UPnP Router Control (https://launchpad.net/upnp-router-control)
![upnp](https://cloud.githubusercontent.com/assets/10101120/12800029/9d0358ac-ca8f-11e5-8572-5cc69728ea60.png)
Icon=upnp-router-control

- RockBox Utility (http://www.rockbox.org/wiki/RockboxUtility)
![rockbox](https://cloud.githubusercontent.com/assets/10101120/12800030/9d03a37a-ca8f-11e5-9c98-fefa7314c77f.png)
Icon=rbutil

- Vertris (http://www.playdeb.net/app/vertris)
![vertris](https://cloud.githubusercontent.com/assets/10101120/12800031/9d041b8e-ca8f-11e5-8ca5-10feb1a917af.png)
Icon=vertris

- DopeWars (http://dopewars.sourceforge.net/)
![dopewars](https://cloud.githubusercontent.com/assets/10101120/12800032/9d07d044-ca8f-11e5-9879-da9601a767be.png)
Icon=dopewars-weed.png

Thanks in advance. And muchas gracias for the best icon theme available on GNU / Linux!

P.S. Desktop file names + paths for all the necessary ones:
/usr/share/applications/cpu-g.desktop
/usr/share/applications/CryptoTE.desktop
/usr/share/applications/dopewars.desktop
/usr/share/applications/ogmrip.desktop
/usr/share/applications/multisystem-liveusb.desktop
/usr/share/applications/multisystem-vbox.desktop
/usr/share/applications/rbutil.desktop
/usr/share/applications/upnp-router-control.desktop
/usr/share/applications/vertris.desktop
/usr/share/applications/x-tile.desktop

P.P.S. MultiSystem appears to also install duplicates of the .desktop files in /usr/local/share/applications.

**Comment by bil-elmoussaoui** [comment] 2016-02-03 22:50
> TriMage (https://trimage.org/)

duplicate of #2746 

> TorBrowser (http://www.webupd8.org/2013/12/tor-browser-bundle-ubuntu-ppa.html)

duplicate of #2078 #2535 

> Doomseeker (http://doomseeker.drdteam.org/)

Duplicate of #2232 #2257 

> Zandronum (https://zandronum.com/)

Duplicate of #2654 

> ECWolf (http://maniacsvault.net/ecwolf/)

Duplicate of #2050 

Please take a look at [Icon Requests](https://github.com/numixproject/numix-icon-theme-circle#icon-requests)

**Comment by bongochong** [comment] 2016-02-03 23:07
fixed, with icons included. if you'd prefer i migrate these to separate entries, let me know.

**Comment by bil-elmoussaoui** [comment] 2016-02-03 23:24
CPU-G & DopeWars are hardcoded, can you add the desktop file names for those applications ? :+1:

**Comment by bongochong** [comment] 2016-02-04 00:02
sure!

**Comment by Foggalong** [comment] 2016-02-04 09:42
I appreciate the thought in not wanting to clog up the tracker, but it'd actually be a lot more useful to have these as seperate issues rather than as a list. There's a lot of different stuff going on here spo please refile like that so we can properly categorise it all :)

**Closed by Foggalong** 2016-02-04 09:42 UTC
