### ISSUE TITLE
Icon for Kollision

### ISSUE THREAD

**Issue by jags9415** [numixproject/numix-icon-theme-circle#2014] opened 2015-04-19 20:48 UTC
**Description:** Icon for Kollision.

```
[Desktop Entry]
Name=Kollision
Exec=kollision
Icon=kollision
Type=Application
Terminal=false
Categories=Qt;KDE;Game;ArcadeGame;X-DocPath=kollision/index.html
```

**Icon:**
![kollision](https://cloud.githubusercontent.com/assets/3059433/7221307/1c4606ea-e6a3-11e4-9b04-1bb689cce777.png)

**Comment by dirtydancing** [comment] 2015-04-19 20:53
Well, this is a duplicate of https://github.com/numixproject/numix-icon-theme-circle/issues/1738. Again, it is recommendable to search the repository first :)

**Closed** 2015-04-19 21:14 UTC
Labels: duplicate
