### ISSUE TITLE
Icon for SmartGitHg

### ISSUE THREAD

**Issue by ghivert** [numixproject/numix-icon-theme-circle#1239] opened 2014-10-29 08:22 UTC
Hey guys !

Just missing an icon for SmartGitHg !
Name=SmartGit/Hg 6
Icon=syntevo-smartgithg-6.png
Original icon : ![77d012c4c585e42b45b4cf8be385de74_400x400](https://cloud.githubusercontent.com/assets/7314118/4822638/a1832a5e-5f44-11e4-9b92-3dae837f5984.png)

**Comment by Foggalong** [comment] 2015-04-05 17:44
Duplicate of #291

**Closed by Foggalong** 2015-04-05 17:44 UTC
Labels: request
