### ISSUE TITLE
Ubuntu 17.10 terminal

### ISSUE THREAD

**Issue by TheNewCivilian** [numixproject/numix-icon-theme-circle#74] opened 2017-12-19 17:44 UTC
No idea how I got this gigant terminal Icon at the right corner of my standard Ubuntu 17.10 terminal.
Using Numix Daily Application Theme with Numix-Circle.
![Standard Ubuntu 17.10 Terminal](https://user-images.githubusercontent.com/24456478/34170617-d6578114-e4eb-11e7-8829-354345ee23e4.png)

**Comment by Godrigos** [comment] 2017-12-22 11:53
Same stuff here. Ubuntu 17.10. Issue appear only at terminal window.
![captura de tela de 2017-12-22 09-49-59](https://user-images.githubusercontent.com/2129268/34297211-ea4945c2-e6fd-11e7-8a72-959505744ad4.png)

**Comment by palob** [comment] 2017-12-22 12:28
Can't reproduce but the pairus guys faced a similar issue https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/453

**Comment by bil-elmoussaoui** [comment] 2017-12-24 17:46
I can't reproduce this neither. The same issue happens with other themes like Paper, Moka...It's rather an issue with either an old gtk version used on Ubuntu 17.10 or some broken stuff on Ubuntu itself.

**Comment by maxdraki** [comment] 2018-02-01 22:07
same issue for me :(

**Comment by Foggalong** [comment] 2018-07-17 21:15
Closed as EOL

**Closed by Foggalong** 2018-07-17 21:15 UTC
Labels: bug
