### ISSUE TITLE
VLC won't launch while numix-circle is in use

### ISSUE THREAD

**Issue by Linkshandigen** [numixproject/numix-icon-theme-circle#1437] opened 2015-01-08 14:20 UTC
VLC has a segmentation fault as soon as I launch it while I am using numix-circle. It seems to work fine otherwise. This is what happens when I launch from terminal:

$ vlc
VLC media player 2.2.0-pre2 Weatherwax (revision 2.2.0-pre1-15-g5178b24)
[00000000010d8118] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Segmentation fault (core dumped)
$

**Comment by dirtydancing** [comment] 2015-01-09 10:30
@Linkshandigen Which distribution are you using? With Ubuntu 14.10, I can NOT replicate your issue. VLC has always started without problems for me on Ubuntu with Numix-Circle. When I launched from Terminal, I got (started just fine):

$ vlc
VLC media player 2.2.0-pre2 Weatherwax (revision 2.2.0-pre1-15-g5178b24)
[0000000001006118] core libvlc: VLC wird mit dem Standard-Interface ausgeführt. Benutzen Sie 'cvlc', um VLC ohne Interface zu verwenden.

**Comment by bil-elmoussaoui** [comment] 2015-01-09 10:32
I confirm that have nothing to do with VLC, try reinstalling the last stable version, upgrade your system and try again ;)
VLC media player 2.2.0-rc2 Weatherwax (revision 2.2.0-rc1-118-g22fda39)
[0000000000acc058] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.

**Comment by Foggalong** [comment] 2015-03-13 20:14
Multiple people running the same version cannot reproduce, so closing this :( If your problem is still happening, your problem is elsewhere I think

**Closed by Foggalong** 2015-03-13 20:14 UTC
Labels: bug
