### ISSUE TITLE
Icon for DevAssistant

### ISSUE THREAD

**Issue by JulienRbt** [numixproject/numix-icon-theme-circle#1797] opened 2015-03-28 20:57 UTC
Please for an icon for DevAssisant, it is an assisant for dev :smiley: 
[Website](http://devassistant.org/)

Original icon:
![DevAssisant](http://devassistant.org/landing_page/da-logo.png)

/usr/share/applications/devassistant.desktop content:
Icon=devassistant

**Comment by palob** [comment] 2015-03-28 21:48
Already present in Numix-Circle master.

**Comment by Foggalong** [comment] 2015-03-28 22:25
Duplicate of #1271. See [here](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/devassistant.svg) for the icon :)

**Closed by Foggalong** 2015-03-28 22:25 UTC
