### ISSUE TITLE
Icon for XFCE preferences-desktop-theme

### ISSUE THREAD

**Issue by vidrafeed** [numixproject/numix-icon-theme-circle#1820] opened 2015-04-01 18:14 UTC
missing icon for Xfce preferences-desktop-theme
Icon=preferences-desktop-theme
![istantanea_2015-04-01_20-11-32](https://cloud.githubusercontent.com/assets/8080711/6948084/b6ff68ee-d8ab-11e4-978a-49395b595930.png)

**Comment by Foggalong** [comment] 2015-04-01 19:10
Duplicate of #927 - it's a Numix Circle icon, it's just not circular :)

**Closed by Foggalong** 2015-04-01 19:10 UTC

**Comment by dirtydancing** [comment] 2015-04-19 20:24
@vidrafeed To let you know: this has now been fixed in https://github.com/numixproject/numix-icon-theme-circle/issues/927 relating to MATE control center, and this fixes it for XFCE, too. I have checked in current Xubuntu 15.04 Beta 2. Screenshot:

![xubuntu1504beta2_preferences](https://cloud.githubusercontent.com/assets/7164227/7221204/7781bf88-e6e2-11e4-8e07-99aa132548f7.png)
