### ISSUE TITLE
Update icon for the new CLion IDE

### ISSUE THREAD

**Issue by btd1337** [numixproject/numix-icon-theme-circle#3110] opened 2016-05-11 16:29 UTC
Update the icon for new CLion IDE

Icon=/opt/clion-2016.1.1/bin/clion.svg

![clion](https://cloud.githubusercontent.com/assets/11943860/15188477/575df674-177c-11e6-9bc3-d5a0132cf370.png)

**Comment by Foggalong** [comment] 2016-05-11 16:54
Duplicate of  #2730

**Closed by Foggalong** 2016-05-11 16:54 UTC
Labels: duplicate
