### ISSUE TITLE
Unreal Engine

### ISSUE THREAD

**Issue by SalahAdDin** [numixproject/numix-icon-theme-circle#2511] opened 2015-08-29 01:12 UTC
Hi man, firts, i say you that i like your icons, are awesome, beautiful, elegant.

I want request you an icon for Unreal Engine, i make one for it but it's very ugly.

Can you help me with it? Thank you.

**Comment by Foggalong** [comment] 2015-08-29 13:56
Duplicate of #2276. Please add the information set out in the README in future too because it makes it easier for us to fulfil requests :)

**Closed by Foggalong** 2015-08-29 13:56 UTC
Labels: duplicate
