### ISSUE TITLE
Icon for frescobaldi

### ISSUE THREAD

**Issue by ace214** [numixproject/numix-icon-theme-circle#1777] opened 2015-03-23 03:32 UTC
A numix-circle icon for frescobaldi is missing.

The icon line says "frescobaldi" as the original icon is attached.

App: http://frescobaldi.org/
![frescobaldi](https://cloud.githubusercontent.com/assets/11447289/6773719/ba9b75c8-d0eb-11e4-9151-085c84487695.png)

**Comment by Foggalong** [comment] 2015-03-23 14:26
Duplicate of  #1180. Are you sure you're running the latest version?
![screenshot - 230315 - 14 25 29](https://cloud.githubusercontent.com/assets/5920259/6781849/8f814f98-d168-11e4-8177-c23979aedc52.png)

**Closed by Foggalong** 2015-03-23 14:26 UTC
Labels: duplicate

**Comment by ace214** [comment] 2015-03-23 15:01
Yes. The original icon changed about a year ago: https://github.com/wbsoft/frescobaldi/commit/e8a79eee1573b1ee1c329e2a8a38e2bc2d2c3ed3

Also, that icon does not show up for me with numix-square.

**Comment by Foggalong** [comment] 2015-03-23 16:50
Yeah, Square is lagging a bit behind until I have time to bring it up to date :(

**Comment by ace214** [comment] 2015-03-23 16:52
No problem- just wanted to bring it to your attention.

Thanks for all your work.
