### ISSUE TITLE
Icon Freecad

### ISSUE THREAD

**Issue by Danlorenzi** [numixproject/numix-icon-theme-circle#2717] opened 2015-12-01 18:53 UTC
Original Icon
![photo jpg](https://cloud.githubusercontent.com/assets/16104714/11510657/ebaf823a-984b-11e5-9bb3-2b6c65d94db6.png)
Proposed icon
![freecad-icon](https://cloud.githubusercontent.com/assets/16104714/11510645/de7c8590-984b-11e5-8583-64243261d702.png)

**Comment by Foggalong** [comment] 2015-12-02 17:36
Looking into this, we do already have a [FreeCad icon](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/freecad.svg). This is a duplicate of #939, sorry! For more information, see the README section on hardcoded icons.

**Closed by Foggalong** 2015-12-02 17:36 UTC
