### ISSUE TITLE
Icon Request for Heartstone

### ISSUE THREAD

**Issue by rickinbsb** [numixproject/numix-icon-theme-circle#2488] opened 2015-08-16 23:27 UTC
It is installed from the Battle.net launcher and opens via wine
![539dc542378dc](https://cloud.githubusercontent.com/assets/4140033/9295926/3c50cc76-4455-11e5-8843-f667b7006861.jpg)

There is already a rounded vector version for this icon on the internet, that can greatly help development: http://uxrepo.com/icon/hearthstone-by-dr-slash

[Desktop Entry]
Name=Hearthstone
Exec=env WINEPREFIX="/home/rick/.wine" wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/rick/.wine/dosdevices/c:/users/Public/Start\\ Menu/Programs/Hearthstone/Hearthstone.lnk
Type=Application
StartupNotify=true
Path=/home/rick/.wine/dosdevices/c:/Program Files (x86)/Hearthstone
Icon=ACAF_Hearthstone Beta Launcher.0

**Comment by Foggalong** [comment] 2015-08-17 11:03
Duplicate of #2137

**Closed by Foggalong** 2015-08-17 11:03 UTC

**Comment by rickinbsb** [comment] 2015-08-17 12:02
Search function of github didn't return that one, sorry

Em seg, 17 de ago de 2015 08:03, Joshua Fogg <notifications@github.com>
escreveu:
