### ISSUE TITLE
Icon for MessengerForDesktop

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-icon-theme-circle#2347] opened 2015-06-23 11:46 UTC
http://messengerfordesktop.com/

[Desktop Entry]
Version=1.0
Type=Application
Name=Messenger
Icon=messengerfordesktop
Exec=/opt/MessengerForDesktop/Messenger
Comment=Messenger for Desktop
Categories=Network;Chat;
Terminal=false
X-Desktop-File-Install-Version=0.22

![messenger](https://cloud.githubusercontent.com/assets/11137173/8305334/4f834f84-19ae-11e5-8adf-13af484e4684.png)

Thanks for your effort.

**Comment by Foggalong** [comment] 2015-06-25 14:16
Duplicate of #2237

**Closed by Foggalong** 2015-06-25 14:16 UTC
Labels: duplicate
