### ISSUE TITLE
Icon for Gcolor2

### ISSUE THREAD

**Issue by ElvisPresly** [numixproject/numix-icon-theme-circle#3162] opened 2016-05-16 11:01 UTC
[Desktop Entry]
Name=Gcolor2
GenericName=Gcolor2
Comment=Simple GTK2 color selector and picker
Exec=gcolor2
Icon=/usr/share/pixmaps/gcolor2/gcolor2.xpm
Terminal=false
Type=Application
Categories=Application;Graphics;

![2016-05-16 13-56-55](https://cloud.githubusercontent.com/assets/18265958/15287871/b8018e32-1b6e-11e6-9abc-ae31d8008e26.png)

**Comment by Foggalong** [comment] 2016-05-16 11:19
Duplicate of #384. See the readme for more information on hardcoded icons

**Closed by Foggalong** 2016-05-16 11:19 UTC
Labels: duplicate

**Comment by ElvisPresly** [comment] 2016-05-16 11:30
good thx

**Comment by palob** [comment] 2016-05-16 12:11
@ElvisPresly By the way, in case it's part of your distribution, there's [gcolor3](https://github.com/Unia/gcolor3).
