### ISSUE TITLE
Icon for ManaPlus

### ISSUE THREAD

**Issue by Meistache** [numixproject/numix-icon-theme-circle#1566] opened 2015-02-10 04:36 UTC
Hello. I would like to request an icon for ManaPlus client app.
![manaplus_icon](https://cloud.githubusercontent.com/assets/5265507/6121587/4956ecd2-b0cd-11e4-9677-5ab9751b9d1e.png)

This is for the desktop entry (I wonder if it's too much)

[Desktop Entry]
Version=1.0
Name=ManaPlus
Comment=A 2D MMORPG client
Exec=manaplus
StartupNotify=false
Terminal=false
Type=Application
Icon=manaplus
Categories=Game;AdventureGame;
Keywords=MMORPG;game;RPG;adventure;multiplayer;online;

This is the only icon lacking on my dock so I'll eagerly wait for it to come :) Thanks!

**Comment by gregorydk** [comment] 2015-02-10 09:39
Duplicate of https://github.com/numixproject/numix-icon-theme-circle/issues/1161

**Closed** 2015-02-10 09:52 UTC
Labels: duplicate
