### ISSUE TITLE
Invalid Cache

### ISSUE THREAD

**Issue by kookerus** [numixproject/numix-icon-theme-circle#2380] opened 2015-07-06 03:01 UTC
Installing any numix icon theme on a fresh install of Ubuntu 14.04 gives an error `gtk-update-icon-cache: The generated cache was invalid.`. When using the theme, most icons are missing.

**Comment by Foggalong** [comment] 2015-07-06 13:54
The cache part is a duplicate of #915 but not sure on this missing icons. Have you tried applying the theme and then logging out and back in?

**Comment by kookerus** [comment] 2015-07-07 01:12
Reinstalling the OS fixed the missing icons, but when they were missing, restarting/relogging didn't help. I also noticed that when attempting to use the numix bevel theme, the only icons that weren't missing were still from the circle theme.

**Comment by Foggalong** [comment] 2015-07-07 01:29
Bevel and Circle are very different structurally now. Bevel is an all inclusive theme while Circle is a modular theme designed to be used with the Base theme. There's separate repo for Bevel on here because of that so if I'm understanding correctly and this is an issue for it you should post there... that said, Bevel isn't officially supported anymore so it's unlikely it'll ever be solved :(

**Closed** 2015-07-08 12:17 UTC
Labels: duplicate
