### ISSUE TITLE
Folder and Updates Icons broken in Kubuntu

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [numixproject/numix-icon-theme-circle#2798] opened 2016-01-20 02:49 UTC
As of the latest update most folder icons and the "updates" icon in the system tray are broken and display blank. I panicked and thought I'd broke my OS so I re-installed Kubuntu fresh. The problem still persists.

**Comment by wa4557** [comment] 2016-01-20 07:24
Can you post a Screenshot?

**Comment by palob** [comment] 2016-01-20 14:25
This being a base issue aside I can confirm:
![snapshot1](https://cloud.githubusercontent.com/assets/7050624/12451434/4cbeee7e-bf81-11e5-8254-b077274925a6.png)


Blank spots instead of folder icons in Dolphin (on Kubuntu 15.10 ISO).
mimetypes/devices/actions/apps... seem OK.

Looks all fine in the KDE filechooser window:
![snapshot2](https://cloud.githubusercontent.com/assets/7050624/12451497/b71df4c2-bf81-11e5-8aaa-9d67639e3d9d.png)

**Comment by Leonivek** [comment] 2016-01-20 14:31
I can confirm the same since the updates received in Ubuntu yesterday.

**Comment by palob** [comment] 2016-01-20 14:33
@Leonivek @KUPOinyourWINDOW Do you encounter breakage anywhere else?
Could you please add a screenshot of that "updates" icon?

**Comment by palob** [comment] 2016-01-20 14:47
Back on GNOME Qt image viewer ``Nomacs`` fails to show the image.

**Comment by KUPOinyourWINDOW** [comment] 2016-01-20 14:49
The missing updates icon in system tray:
![screenshot 2016-01-20 14 42 56](https://cloud.githubusercontent.com/assets/7698035/12452159/e5f76c12-bf84-11e5-9d83-07699eef3acb.png)

The missing updates icon within Muon Update Manager:
![screenshot 2016-01-20 14 43 26](https://cloud.githubusercontent.com/assets/7698035/12452168/f34527d8-bf84-11e5-8007-ea8a6b2dae96.png)

(P.S forgive my noobiness, I absolutely love Numix Circle and want to help)

**Comment by leandronn** [comment] 2016-01-20 16:40
Hi, this is what happens when running dolphin from terminal


Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/16x16/panel"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/22x22/panel"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/24x24/panel"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/16/panel"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/16@2x/panel"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/22/panel"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/22@2x/panel"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/24/panel"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/24@2x/panel"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Numix/48/notifications"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Numix/48@2x/notifications"
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Numix/64/apps"
Icon theme "gnome" not found.

![snapshot1](https://cloud.githubusercontent.com/assets/6962148/12455662/4796b478-bf7b-11e5-900c-1281dde85249.png)

**Comment by KUPOinyourWINDOW** [comment] 2016-01-20 17:59
There is also an icon missing in the "Muon Discovery" app store when you go to give permissions for installing an app.
![screenshot 2016-01-20 17 58 50](https://cloud.githubusercontent.com/assets/7698035/12458025/80e68dce-bf9f-11e5-9676-7290370b354f.png)

**Comment by wa4557** [comment] 2016-01-20 18:36
I cannot reproduce this. With dolphn and `nomacs` everything fine here on Ubuntu (although there are some small transparancy issues in Qt appearantly)

**Comment by bil-elmoussaoui** [comment] 2016-01-20 19:01
The missing icons in KDE be fixed by adding the default theme in KDE to  `Inherits = gnome`?

**Comment by palob** [comment] 2016-01-20 21:38
@wa4557 15.10 or 16.04? Nomacs 3.0 using Qt5?

**Comment by wa4557** [comment] 2016-01-20 21:51
15.10. Yeah the invalid context warnings are definitely not the issue. Something with the cleaning seems to have broken the icons for Qt

**Comment by leandronn** [comment] 2016-01-20 21:51
15.10 here

**Comment by KUPOinyourWINDOW** [comment] 2016-01-20 21:53
I'd like to add that the the screenshots I've shared have displayed missing icons that were there before the most recent update so I think Numix does cover them. Also folder icons in Dolphin are also missing for me just like the screenshot someone else shared above.

**Comment by wa4557** [comment] 2016-01-20 22:00
@palob Can you name an icon that is broken? (and one that is definitely working as well maybe)

**Comment by palob** [comment] 2016-01-20 22:00
@wa4557 My first guess is that it's got something to do with those shadows beneath the folder icons.

There's somthing strange with those, I can't select them in Inkscape even in a revesion before your maintenance commits.

**Comment by wa4557** [comment] 2016-01-20 22:01
Maybe a different layer?

**Comment by palob** [comment] 2016-01-20 22:07
Strangely enough Nomacs (2.4.6 from the Arch repo here, still using **Qt4**) displays the icon correctly in the thumbnail preview.

**Comment by wa4557** [comment] 2016-01-20 22:08
My Qt testing script which is using Qt5 has no problems with for example `folder-home` (Not sure if this is one of the broken ones)

**Comment by palob** [comment] 2016-01-20 22:10
Actually your commits repaired the icons in the way I'm now able to catch the shadow object.

Yep, ``folder-home`` is amongst the broken ones.

**Comment by wa4557** [comment] 2016-01-20 22:17
Does the problem also happens if you use a different style?

**Comment by palob** [comment] 2016-01-20 22:19
Need to try. Maybe it's a Qt4-only issue? Dolphin [still depends on KDELibs4](http://developer.kde.org/~cfeck/portingstatus.html) and thus Qt4. Well, wondering why it works for you.

**Comment by palob** [comment] 2016-01-20 22:34
Comparing the SVG sources before your commit there were hell of a lot ``linearGradient`` objects I don't know where those would have been used. 
Now it's down to 1 of them.

**Comment by palob** [comment] 2016-01-20 23:02
That's really strange...
When browsing ``/usr/share/icons/Numix/.../places/`` Dolphin shows the icon preview correctly.
Everything works smooth when viewing in Gwenview or Nomacs 3.0 as well.

However I found 2 icons looking genuinely broken:
![snapshot1](https://cloud.githubusercontent.com/assets/7050624/12466092/d5800340-bfc9-11e5-9550-48e2ed4d0a1a.png)
![snapshot2](https://cloud.githubusercontent.com/assets/7050624/12466091/d57f5fee-bfc9-11e5-98d5-bae808176c63.png)

**Comment by KUPOinyourWINDOW** [comment] 2016-01-20 23:29
Just a heads up, I just received an update on Kubuntu but it hasn't fixed the issue so the bug still stands.

**Comment by palob** [comment] 2016-01-21 00:13
@wa4557 Are you sure you used the latest git when testing with Dolphin/Nomacs?

**Comment by leandronn** [comment] 2016-01-21 16:32
@palob I've cloned latest git with Dolphin

**Comment by palob** [comment] 2016-01-21 16:44
@KUPOinyourWINDOW Can you post screenshots of the missing non-folder icons when using the ``breeze`` theme or even better do know know what's those icons' names?

**Comment by leandronn** [comment] 2016-01-21 16:53
Also, file chooser when opening (for example) via Kate editor, is not working.

![snapshot2](https://cloud.githubusercontent.com/assets/6962148/12487514/4aeb5ce8-c046-11e5-8eec-7d8ddf279683.png)

**Comment by leandronn** [comment] 2016-01-21 16:55
@bil-elmoussaoui Added Inherits=gnome to default theme index.theme but none happens.

**Comment by palob** [comment] 2016-01-21 16:58
@leandronn As I said, that isn't related.
How does it look in the ``KSnapshot`` filechooser when saving a screenshot. It did work for me there.

**Comment by leandronn** [comment] 2016-01-21 17:00
@palob there it works ok. Sorry I didn't see you saying that. Just trying to help. I'm not an expert linux user.
![snapshot3](https://cloud.githubusercontent.com/assets/6962148/12487733/38c4975e-c047-11e5-9061-d2a688d99b38.png)

**Comment by KUPOinyourWINDOW** [comment] 2016-01-21 17:05
I don't know the names but here are some screenshots! 
Updates System Tray icon: 
![screenshot 2016-01-21 17 01 21](https://cloud.githubusercontent.com/assets/7698035/12487902/112e7a1a-c061-11e5-9ead-cc7962d80119.png)

Muon Update Manager icon: 
![screenshot 2016-01-21 17 02 01](https://cloud.githubusercontent.com/assets/7698035/12487894/0ac29c24-c061-11e5-8ad2-c2677b76d29a.png)

Muon Discover (App Store) icon:
![screenshot 2016-01-21 17 03 00](https://cloud.githubusercontent.com/assets/7698035/12487939/2bc6e8e4-c061-11e5-99fa-4ed65ce8e826.png)

**Comment by palob** [comment] 2016-01-21 17:26
@KUPOinyourWINDOW Thanks. Both were showing up correctly before the update?

**Comment by KUPOinyourWINDOW** [comment] 2016-01-21 18:04
Yep, everything I've shared on this bug report was showing fine before the update. It's actually before the most recent two updates now though as I got one yesterday that didn't fix the issue.

**Comment by Leonivek** [comment] 2016-01-21 18:17
FYI, all of the screenshots showing the issue in this report is exactly the same for me since that second to last update, but all other themes work fine. And all is fine in GNOME Shell, too.

**Comment by wa4557** [comment] 2016-01-21 19:23
@palob Yes using the latest version from git. No brekages in `nomacs` or dolphin. 

The "Updates" icon seems to be `security-high`. Nothing weird with this icon though

**Comment by KUPOinyourWINDOW** [comment] 2016-01-21 20:01
@palob there is also an update that is missing for when an update is available but hasn't been downloaded. This is what it looks like in the Breeze icon theme when the icon is visible (the shield):
![screenshot 2016-01-21 20 00 26](https://cloud.githubusercontent.com/assets/7698035/12492767/be88f3ee-c079-11e5-9624-6c04ca829273.png)

**Comment by KUPOinyourWINDOW** [comment] 2016-01-22 04:20
@palob I have also found a new icon that is missing from Numix Circle. It's the icon that should show when giving permissions to an application locally stored (not from the muon discover app) on the computer. This is how it looks in the Breeze icon theme:
![screenshot 2016-01-22 04 17 53](https://cloud.githubusercontent.com/assets/7698035/12502328/655002ea-c0bf-11e5-89f2-baccb7c69d01.png)

**Comment by palob** [comment] 2016-01-22 12:38
Wow, dat Qt SVG!

**Seems I've got the fix:**

After deleting the first comment line
```
<!-- Created with Inkscape (http://www.inkscape.org/) -->
```
the icons do show up correctly in Nomacs 2.4.6

@KUPOinyourWINDOW @Leonivek @leandronn Can you open ``/usr/share/icons/Numix/48/places/default-folder.svg`` in a text editor and delete the first line shown above?

Does it help? You might need to adjust the icon size in Dolphin as that's only the 48px X 8px size.

**Comment by wa4557** [comment] 2016-01-22 12:40
That's great news! This can be easily implemented into the svgcleaner-script! I wonder why this wasn't a problem before...

**Comment by leandronn** [comment] 2016-01-22 12:41
Great!. Works like a charm.

**Comment by palob** [comment] 2016-01-22 12:48
@wa4557 OK, so let's do this batch-wise. Those opacity issues I've shown [above](https://github.com/numixproject/numix-icon-theme-circle/issues/2798#issuecomment-173392700) need to be fixed manually I'm afraid. Paths with sub-100%-opacity need to be transformed to the apparant colour using 100% opacity.

**Comment by KUPOinyourWINDOW** [comment] 2016-01-22 15:42
It works, when I delete that line the normal folder icons appear correctly in Dolphin at the size you said above. There still are missing icons though so I assume the other missing icons need too have that line removed too. Thank you for your effort, can't wait to get back to using this icon theme!

**Comment by wa4557** [comment] 2016-01-22 15:47
@palob The opacity issue was there even before the maintenance ,but yeah they need to be changed manually. 
I can do a removal of these "inkscape" lines this evening. Not so sure about the other opacity issues. Shadows in Numix-circle seem to be ok on KDE as well

**Comment by palob** [comment] 2016-01-22 16:13
@wa4557 I can fix the opacity issues this or the next weekend.

**Comment by Foggalong** [comment] 2016-01-22 16:34
@KUPOinyourWINDOW what's going on with your Firefox icon?

**Comment by KUPOinyourWINDOW** [comment] 2016-01-22 17:17
@Foggalong I'm assuming you mean why is it greyed out in some of my screenshots. That's because it's open but minimized. That's either a feature of KDE or a feature of the theme I'm using for it.

**Comment by Foggalong** [comment] 2016-01-22 17:40
@KUPOinyourWINDOW huh, cool!

**Comment by wa4557** [comment] 2016-01-23 11:53
@palob Regarding your question about different colours: [Folder Colour](https://launchpad.net/folder-color) needs them

**Comment by wa4557** [comment] 2016-01-23 13:32
This should be fixed now...

**Comment by KUPOinyourWINDOW** [comment] 2016-01-23 17:21
Yep, you've fixed the issue, I can finally go back to having a good looking Linux desktop, thank you! There are still a few "missing" icons for app store download verification and local app password verification but I'm not sure if they were there to begin with. It's up to you if you wanna look into this or not, they're prompts not seen very often or for very long so it's not a big deal.

**Comment by Leonivek** [comment] 2016-01-23 17:22
Yay! :)  My desktop looks sexy again.

**Comment by palob** [comment] 2016-01-23 17:34
@KUPOinyourWINDOW 
Do you get blank spots in place of that missing icons? That might be icons we don't cover yet without ``Oxygen`` (which as far as I can see is the default fallback theme) icon.

In order to get rid of the blank spots and have ``breeze`` icons instead, can you open ``/usr/share/icons/Numix/index.theme`` in a text editor and add ``breeze`` to the inheritance line, like ``Inherits=breeze,...``

**Comment by delacruzbordajn** [comment] 2016-01-23 18:01
Thank you guys so really much! Seriously, I don't have any money I'm just an Information Systems Engeneering student but I know that I want, in some way, to collaborate (Sorry for my poor english I'm Spanish-Speaking).

**Comment by KUPOinyourWINDOW** [comment] 2016-01-23 19:04
I think you're right @palob about them being icons you don't cover yet. The icon theme is fixed though and I'm happy with that! Thanks again.

**Comment by Foggalong** [comment] 2016-01-23 19:33
Is this all fixed up now then? :smile:

**Comment by leandronn** [comment] 2016-01-24 19:00
Great work. Thank you so much.

**Comment by palob** [comment] 2016-01-25 16:31
@Foggalong All fixed. I've created a seperate issues for the unrelated opacity issue https://github.com/numixproject/numix-icon-theme/issues/1001

**Comment by Foggalong** [comment] 2016-01-25 17:27
Awesome, thanks :+1:

**Closed by Foggalong** 2016-01-25 17:27 UTC
Labels: bug
