### ISSUE TITLE
Icon for Tor Browser

### ISSUE THREAD

**Issue by bulu009** [numixproject/numix-icon-theme-circle#6] opened 2016-08-28 06:34 UTC
A numix-circle icon for Tor Browser is missing

[Desktop Entry]
Version=1.0
Type=Application
Name=Tor Browser
Exec=/usr/bin/tor-browser-en.sh
Icon=/usr/share/pixmaps/tor-browser-en.png
Categories=Network;
Comment=Tor Browser Bundle: Anonymous browsing using Firefox and Tor

Original icon is attatched:

![tor original icon](https://cloud.githubusercontent.com/assets/20025882/18032051/7d45e5ae-6d17-11e6-819a-163e0608d031.png)

**Comment by palob** [comment] 2016-08-29 06:43
duplicate of https://github.com/numixproject/circle-core/issues/2983

The icon is hardcoded, cf. https://github.com/numixproject/circle-core#hardcoded-icons

**Comment by bulu009** [comment] 2016-08-29 10:55
Thank you so much...

**Closed** 2016-08-29 10:55 UTC
