### ISSUE TITLE
Icon for FoxIt

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2685] opened 2015-11-17 14:51 UTC
[FoxIt](https://www.foxitsoftware.com) is a pdf viewer 

- The launcher: `FoxitReader.desktop`
- Launcher Path: `/home/leco/.local/share/applications`
- (Hardcoded) icon name: `FoxitReader.png`

- Default icon:
![foxitreader](https://cloud.githubusercontent.com/assets/1277920/11214687/cd4d1960-8d29-11e5-9dd6-d8c5cc254878.png)

**Comment by Foggalong** [comment] 2015-11-17 15:49
Duplicate of #2581

**Closed by Foggalong** 2015-11-17 15:49 UTC
Labels: duplicate
