### ISSUE TITLE
Icon for GitKraken

### ISSUE THREAD

**Issue by nbbeeken** [numixproject/numix-icon-theme-circle#2990] opened 2016-04-18 04:20 UTC
It would be awesome to have an icon for GitKraken.
The icon line is "app", I included the rest of the desktop file just in case below

Here is the original icon.
![gitkrakenicon](https://cloud.githubusercontent.com/assets/10873993/14593639/0316e5fa-04fb-11e6-970a-2858dc542971.png)

Here's the .desktop file
```
[Desktop Entry]
Name=GitKraken
Comment=Unleash your repo
GenericName=Demo Application
Exec=/usr/share/gitkraken/gitkraken %U
Icon=app
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Development;Documentation;
MimeType=text/plain;
```

**Comment by Foggalong** [comment] 2016-04-18 08:04
Duplicate of #2880

**Closed by Foggalong** 2016-04-18 08:04 UTC
Labels: duplicate
