### ISSUE TITLE
Icon for sunflower-fm

### ISSUE THREAD

**Issue by Keops1984** [numixproject/numix-icon-theme-circle#1343] opened 2014-11-29 09:18 UTC
Small and highly customizable twin-panel file manager for Linux

http://sunflower-fm.org/

![image](https://cloud.githubusercontent.com/assets/2146560/5234057/bf9cad4c-77b0-11e4-9178-5b43a86607c8.png)

thanks..

**Comment by Foggalong** [comment] 2015-04-02 23:23
Duplicate of #1037 which has now been fixed :)

**Closed by Foggalong** 2015-04-02 23:23 UTC
Labels: request
