### ISSUE TITLE
The generated cache was invalid.

### ISSUE THREAD

**Issue by maxdraki** [numixproject/numix-icon-theme-circle#1811] opened 2015-03-30 18:24 UTC
I'm getting an icon cache error - is this a bug in the theme, or do you think it's an Ubuntu thing?

thanks

*'Preparing to unpack .../numix-icon-theme-circle_1.0.2+3~201502071451~ubuntu14.10.1_all.deb ...
Unpacking numix-icon-theme-circle (1.0.2+3~201502071451~ubuntu14.10.1) over (1.0.2+3~201502071451~ubuntu14.10.1) ...
gtk-update-icon-cache-3.0: The generated cache was invalid.
WARNING: icon cache generation failed for /usr/share/icons/Numix-Circle
gtk-update-icon-cache-3.0: The generated cache was invalid.
WARNING: icon cache generation failed for /usr/share/icons/Numix-Circle-Light'*

**Comment by Foggalong** [comment] 2015-03-30 18:41
Duplicate of [#915](https://github.com/numixproject/numix-icon-theme-circle/issues/915). We've pushed a fix, it's just not in the PPA yet :)

**Closed** 2015-03-30 19:19 UTC
Labels: duplicate

**Comment by maxdraki** [comment] 2015-03-30 21:25
Ah - sorry, I had a look for an existing bug - but obviously didn't look hard enough! Thanks for the response

**Comment by Foggalong** [comment] 2015-03-30 21:27
Not a problem! :)
