### ISSUE TITLE
Icon for Enthought Canopy

### ISSUE THREAD

**Issue by kuravih** [numixproject/numix-icon-theme-circle#1520] opened 2015-01-30 16:08 UTC
Icon for Canopy, Python distribution by Enthought
https://www.enthought.com/products/canopy/

Icon=Icon=/opt/Canopy/canopy.png

![canopy](https://cloud.githubusercontent.com/assets/7969796/5978790/5eefad6e-a870-11e4-8728-1cb9a9588936.png)

**Comment by Foggalong** [comment] 2015-04-03 15:54
Duplicate of  #323

**Closed by Foggalong** 2015-04-03 15:54 UTC
Labels: hardcoded, request
