### ISSUE TITLE
gpg: keyserver receive failed

### ISSUE THREAD

**Issue by gamesbook** [numixproject/numix-icon-theme-circle#120] opened 2020-03-13 16:56 UTC
When trying to run:

`sudo add-apt-repository ppa:numix/ppa`

I get this error:

`You are about to add the following PPA:
The official PPA for the Numix Project - http://numixproject.org
The PPA consists of various artwork packages from the Numix Project.
More info: https://launchpad.net/~numix/+archive/ubuntu/ppa
Press Enter to continue or Ctrl+C to cancel
Executing: /tmp/apt-key-gpghome.b5vbfx7jG1/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 43E076121739DEE5FB96BBED52B709720F164EEB
gpg: keyserver receive failed: Server indicated a failure`

**Comment by Foggalong** [comment] 2020-03-20 16:08
Which distribution are you using? That command works for me on 18.04 LTS

**Comment by Foggalong** [comment] 2020-07-11 12:27
Closing this due to lack of information. If you're still having this problem @gamesbook let me know, but I haven't been able to reproduce this on either of current Ubuntu releases.

**Closed by Foggalong** 2020-07-11 12:27 UTC
Labels: bug
