### ISSUE TITLE
Icon for XDM

### ISSUE THREAD

**Issue by arcleise** [numixproject/numix-icon-theme-circle#1213] opened 2014-10-14 17:50 UTC
Xtreme Download Manager
http://xdman.sourceforge.net/index.html

![image](https://cloud.githubusercontent.com/assets/6587144/4633794/920dc94c-53ca-11e4-80d8-98350ddb02ed.png)

**Comment by Foggalong** [comment] 2015-04-05 18:45
Duplicate of #1339

**Closed by Foggalong** 2015-04-05 18:45 UTC
Labels: request
