### ISSUE TITLE
Bluetooth round indicator icon?

### ISSUE THREAD

**Issue by brunces** [numixproject/numix-icon-theme-circle#2274] opened 2015-06-12 12:29 UTC
Hey, guys.

Maybe you don't consider this an issue, but I'd like to talk about it for a little, if you don't mind.

![screenshot_2015-06-12_08-42-27](https://cloud.githubusercontent.com/assets/7181488/8129798/0da86c08-10e3-11e5-8bb3-e8773661567a.png)

I understand that the bluetooth icon shows statuses (disabled, enabled, active) and that those statuses are known by different colors (grey, blue, green). That's great! I also understand that those colors cannot be applied to the bluetooth symbol itself only because people change the color of their panels and, depending on the color, the bluetooth symbol might not appear correctly.

That said, I totally understand the need of a background color for the bluetooth indicator icon. What I don't understand, however, is why it has to be round. Of course, if we consider the "circle" approach of the theme, it totally makes sense. However, IMHO, round icons do not fit well in panels. Even using a round icon theme like Numix Circle, I would still prefer to have square indicator icons on the panel. For instance, mouse over panel icons shows square highlights, hence a square icon makes more sense once it's highlighted.

I know this is all a matter of taste and it's just my opinion. While I don't like it, thousands of other people do, so please don't get me wrong. I just wanted to bring this thought up anyway.

Like I said before, maybe you don't consider this an issue and, if you don't, feel free to close this ticket. Now, if you think I have a point, maybe you could consider it.

Thanks for your attention, guys. I really appreciate it.

Cheers. :)

**Comment by dirtydancing** [comment] 2015-06-12 13:40
@brunces Which distribution is this? And which version of Numix-Circle are you using (PPA/git)?

imo, you are totally correct in raising this issue: This looks like a Numix-Circle icon, and those should not be displayed in the panel. The bluetooth icons exist in Numix base as well, and for the panel should be taken from there. This being said, the panel icons situation is an issue e.g. addressed in (the long) https://github.com/numixproject/numix-icon-theme/issues/190. And the bluetooth icons specifically are also in discussion, cf. e.g. https://github.com/numixproject/numix-icon-theme/issues/438. So this appears to be a known issue, just not yet entirely fixed.

The bluetooth indicator icon is a Numix base issue, so Numix-Circle probably is not the right place to discuss this.

**Closed** 2015-06-12 14:21 UTC
Labels: duplicate

**Comment by brunces** [comment] 2015-06-12 14:41
Hi, dirtydancing.

First of all, you're right, the bluetooth indicator icon is a Numix base issue, not a Numix-Circle one. I hadn't thought about that. I apologize for raising the issue here.

I'm using Xubuntu 15.04, as you can see in the screenshot below.

![shot](https://cloud.githubusercontent.com/assets/7181488/8132320/53d42762-10f7-11e5-902b-8f06e915c603.png)

I use Numix Circle from the PPA, so I believe I have the latest version installed.

Anyway, I see you agree with me, so I hope you guys can fix the issue. :)

Thank you very much for your attention. :)

**Comment by dirtydancing** [comment] 2015-06-12 15:42
@brunces Although the Bluetooth indicator issue is a Numix base issue, the fix for this one might include changes in Numix-Circle, so your issue report here might actually not be as far off as you might think :)

Anyways, in the meantime, you might try and remove/rename a couple of `bluetooth` "status" icons from `48x48/apps` in Numix-Circle and see if those from Numix base are displayed then in your panel (Numix-Circle inherits from Numix). This may also be a case of Xubuntu 15.04 using a special Bluetooth icon (?).

Just to let you know: Numix base via PPA is current and updates daily as far as I know, but Numix-Circle via PPA currently is from 7 February 2015 and thus a couple of months behind GitHub. Numix-Circle via PPA is on hold mainly because of the already mentioned https://github.com/numixproject/numix-icon-theme/issues/190.

**Comment by brunces** [comment] 2015-06-12 16:49
Hey, dirtydancing. I did what you suggested and, after logging out and back in, here's the result:

![screenshot_2015-06-12_13-36-26](https://cloud.githubusercontent.com/assets/7181488/8134777/3facf8f2-1108-11e5-8176-c37d185811c1.png)

The icons I renamed were: bluetooth.svg, bluetooth-48.svg, bluetooth-active.svg, bluetooth-black.svg, bluetooth-inactive.svg, bt-logo.svg.

By the way, here's the bluetooth info in Xubuntu...

![screenshot_2015-06-12_13-43-19](https://cloud.githubusercontent.com/assets/7181488/8134879/3cd5beec-1109-11e5-8b52-6750f81e429a.png)

... and the icons (symlinks) related to it are: blueman.svg, blueman-disabled.svg, blueman-active.svg.

I hope this is useful. Cheers. :)

**Comment by dirtydancing** [comment] 2015-06-12 18:48
Did you manage to get the monochrome bluetooth/blueman icon into the panel? `blueman-active.svg` and `blueman-disabled.svg` are e.g. in Numix base in `24x24/status`, so they should be displayed in the Xubuntu panel.

Your first screenshot looks like this might be an icon cache issue. Please try to update the icon cache `sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle` and `sudo gtk-update-icon-cache -f /usr/share/icons/Numix`. Then restart.

**Comment by wa4557** [comment] 2015-06-12 18:55
@dirtydancing I rather think this happens because he's broken the blueman symlinks (It seems that he is using blueman not bluetooth). 

@brunces Try removing the (now broken) `blueman` icons as well from `circle` then the correct icons from base should be used

**Comment by dirtydancing** [comment] 2015-06-12 19:47
@wa4557 Yeah, this might also be the case. Problem is I am not on Ubuntu and thus cannot reproduce this. Plus, the PPA version of Numix-Circle is very different from the GitHub one. E.g., in the Numix-Circle PPA version, there are still bluetooth/blueman icons in the smaller fixed size directories.

@brunces I guess you get the idea what this is about :) Please let us know how we can be of help.

**Comment by brunces** [comment] 2015-06-12 21:27
Hi, @dirtydancing, @wa4557,

Thanks for your replies. I do get the idea of how to "fix" the bluetooth icon...

![screenshot_2015-06-12_18-02-00](https://cloud.githubusercontent.com/assets/7181488/8139900/94cc9ffc-112d-11e5-94d4-20b6a56eb54d.png)

... however, I do not want to use monochrome icons. I didn't mention this before and I apologize for that. I like the colored icons. Like I said before, I totally understand the need of a background color for the bluetooth indicator icon and I love it. The only thing I'm not fond of is the round shape.

When you suggested that I removed/renamed the bluetooth "status" icons from 48x48/apps, I thought it would bring me "colored icons" from the Numix base. By the way, dirtydancing, you were right, there was an icon cache issue in that screenshot of mine. I had forgotten about cache and I only figured it out after I had posted that. Anyway, I thought there were colored bluetooth icons in Numix base (the icons themselves, not their background), but they are just plain monochrome icons with a subtle difference between active and disabled.

Although I don't like the round shape, I prefer to use the Numix Circle icons over the monochrome ones; just because of the colors, for I truly think they are helpful.

That said, I hope you can "fix" the Numix base bluetooth icons, adding colors to them.

Thank you very much for your attention. You guys are really attentive and that's one of reasons why Numix is the best! :)

Cheers. :)

**Comment by wa4557** [comment] 2015-06-12 21:35
@brunces I get what you mean, but I'm afraid this won't happen. The status icons are designed to be monochrome (with the exception of a red colour for a error status, a blue colour for new messages when using messaging tray icons and orange for attention) Thus a coloured version of the bluetooth icon would break the design guidelines

That being said, I'm not @dirtydancing and myself are not numix devs, so if you want this to happen you have to address your concerns to @Foggalong or another numix-dev (although I think they will agree with me here). 

Btw: what's the unthemed icon on the left side of your panel?

**Comment by dirtydancing** [comment] 2015-06-12 22:01
@brunces Wow, this is a surprising turn, coloured status icons instead of monochrome ones! Just like @wa4557, I strongly doubt that that will happen, but you might try your luck with a new issue report for that over at Numix base :) I would actually advise against it, but hey, I am always open to arguments. 

Arguments for the monochrome Bluetooth (panel) indicator icons include consistency with all other panel icons. All the panel status icons were recently redesigned to be a tad lighter and without drop shadow, so they look better esp. on transparent panels. And coloured status icons like you prefer could actually cause problems on transparent panels, just imagine a blue "B" Bluetooth/Blueman status icon on a blue background (will not be well visible). And how about Numix and Numix-Light: light blue for Numix, dark blue for Numix-Light? Sounds somewhat complicated to me.

In your special preference of "square" Bluetooth "status" icons, you might actually go for **Numix-Square** and replace the relevant Circle icons with Square icons. Everyone happy without a default change :)

**Comment by brunces** [comment] 2015-06-12 22:16
Hey, guys.

I could swear I had already seen a blue bluetooth indicator icon before. (lol) Maybe it was of the icon set I used to use before Numix, and I'm probably getting confused.

Anyway, if you guys say it won't happen, I think I'll reconsider the hypothesis of using monochrome icons. I really like the colors, but having the round shapes on the panel "forever" was not part of my plan. I could do with it while waiting for a possible "fix", but not forever. (lol) It really annoys me.

Your suggestion about the Numix-Square makes sense, @dirtydancing. I liked it. Actually, I would love to use Numix-Square. I have already bought it from DeviantArt, but I quit using it because; first, there's no PPA, so the updates must be done manually; and second, the last update on DeviantArt is from 25/12/2014. Maybe I'm wrong but it seems the Square icons don't get the same attention as the Circle ones, which is unfair, in my opinion, because Numix-Square is paid and Numix-Circle is free, so...

I understand the panel issue, dirtydancing. As a matter of fact, I mentioned it on my first post. That's really complicated, yes. :)

The unthemed icon on the left side is GoldenDict, @wa4557, but it's hardcoded and temporary icons, and the files always get their names changed after rebooting. We've already tried to have them monochromed, by the way...

https://github.com/numixproject/numix-icon-theme-circle/issues/566

Thank you guys very much for your attention. Cheers. :)

**Comment by Foggalong** [comment] 2015-07-08 11:13
The problem with Square at the moment is it needs completely redoing from scratch to account for a slight design change. Based on previous work it will take about 3-4 days of straight icon work to do it which means I have to have a let of time set aside for it. It will be done soon I hope, but I can't give an exact date :)
