### ISSUE TITLE
Icon for VeraCrypt

### ISSUE THREAD

**Issue by noam09** [numixproject/numix-icon-theme-circle#3109] opened 2016-05-11 14:24 UTC
A numix-circle icon for veracrypt is missing.
URL: https://veracrypt.codeplex.com/
Original icon location:
`/usr/share/pixmaps/veracrypt.xpm`
Original icon:
![veracrypt xpm](https://cloud.githubusercontent.com/assets/564674/15184441/d9cec13a-179d-11e6-9a64-a8dcaf3a3da9.png)

I couldn't find a "Submissions" page, but here's an icon I made if it saves you the time:
[veracrypt.svg.txt](https://github.com/numixproject/numix-icon-theme-circle/files/259506/veracrypt.svg.txt)

Thanks!

**Comment by Foggalong** [comment] 2016-05-11 16:49
Duplicate of #2803

**Closed by Foggalong** 2016-05-11 16:49 UTC
Labels: duplicate
