### ISSUE TITLE
Icon for Cryptocat

### ISSUE THREAD

**Issue by NIXOYE** [numixproject/numix-icon-theme-circle#3163] opened 2016-05-16 20:41 UTC
Application name: Cryptocat
```
[Desktop Entry]
Name=Cryptocat
Exec=/home/navi/Documents/Cryptocat-linux-x64/Cryptocat
Icon=/home/navi/Documents/Cryptocat-linux-x64/logo.png
Terminal=false
Type=Application
Categories=GNOME;GTK;Network;InstantMessaging;
Comment=Easy, secure chat for your computer.

```
project website https://crypto.cat
original icon
![logo](https://cloud.githubusercontent.com/assets/12674582/15303292/01403d4e-1b85-11e6-880f-983e581302cf.png)

**Comment by Foggalong** [comment] 2016-05-16 20:44
Duplicate of #3021

**Closed by Foggalong** 2016-05-16 20:44 UTC
Labels: duplicate
