### ISSUE TITLE
Icon for VeraCrypt

### ISSUE THREAD

**Issue by pavelxdd** [numixproject/numix-icon-theme-circle#2989] opened 2016-04-18 01:22 UTC
VeraCrypt is a data encryption software based on TrueCrypt.
Icon name `Icon=veracrypt.xpm`
Original icon:
![veracrypt](https://cloud.githubusercontent.com/assets/7561226/14591606/72f419e0-0525-11e6-9e69-8b37c2608926.png)

**Comment by Foggalong** [comment] 2016-04-18 08:05
Duplicate of #2803

**Closed by Foggalong** 2016-04-18 08:05 UTC
Labels: duplicate
