### ISSUE TITLE
MATE Control Center shows non-circle icons

### ISSUE THREAD

**Issue by nsemrau** [numixproject/numix-icon-theme-circle#927] opened 2014-06-16 22:51 UTC
Most of the icons in MATE Control Center are covered by Numix Circle. As you can see on this screenshot, two icons stick out:

![mate-control-center](https://cloud.githubusercontent.com/assets/4363876/3294226/a57d1a56-f5a5-11e3-8c0a-3799634e60fe.png)

`Appearance` uses `/apps/preferences-desktop-theme.svg`, while `Windows` uses `/apps/preferences-system-windows.svg`. Is this form intentional or could they be turned into circled versions?

I am asking because similar-looking circled versions of these icons already exist in Numix Circle and were designed for the related Cinnamon Control Center (`/apps/cs-*.svg`). Maybe these could be used for MATE as well?

**Comment by bil-elmoussaoui** [comment] 2015-04-06 00:27
The Numix designers decided to not use a circular icon for the categories(they are used in Ubuntu software center) . And the MATE preferences uses a category icon instead of an application icon. So this will not be fixed only if the designers change their idea about the categories.

**Comment by wa4557** [comment] 2015-04-19 10:55
The problem is, that these icons are not properly designed in numix-circle. I'd suggest to make circle icons out of them, or remove them completely from circle (prefered solution imo (?))
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/7219167/3d645864-e693-11e4-8da4-3cbfab7403ec.png)

**Comment by Foggalong** [comment] 2015-04-19 11:47
Those two aren't categories so should be Circle icons. I have no idea why they've shown up there O.o

**Comment by wa4557** [comment] 2015-04-19 11:53
Yeah me neither. Symlinking to cs-themes.svg and gnome-window-manager.svg should solve the problem !?

**Comment by Foggalong** [comment] 2015-04-19 11:56
Yeah, good thinking. Do you want to do it or shall I?

**Comment by wa4557** [comment] 2015-04-19 12:28
I'll do it

**Comment by Foggalong** [comment] 2015-04-19 12:29
:+1:

**Comment by dirtydancing** [comment] 2015-04-19 18:16
Does this also go for `preferences-desktop-theme.svg` and `preferences-desktop-screensaver.svg`? :)

![preferences](https://cloud.githubusercontent.com/assets/7164227/7220660/e15ed77c-e6d0-11e4-9366-003f0c67dd98.png)

**Comment by Foggalong** [comment] 2015-04-19 18:45
Probably yeah. Do we have a screensaver icon already?

**Comment by dirtydancing** [comment] 2015-04-19 19:21
Well, so far I have come across `screensaver.svg`, but that is a symlink with the target `preferences-desktop-screensaver.svg`.

I always thought these were intentionally non-Circle icons in Numix-Circle. Then, there is also `preferences-calendar-and-tasks.svg`, also non-Circle, but I am not sure where that is actually used.

![preferences_2](https://cloud.githubusercontent.com/assets/7164227/7220911/e209effa-e6d9-11e4-899f-0951c980b514.png)

**Comment by wa4557** [comment] 2015-04-19 19:22
see here: https://github.com/numixproject/numix-icon-theme/issues/136

**Comment by dirtydancing** [comment] 2015-04-19 19:28
@wa4557 If I understand correctly, that is about `calendar.svg`, which probably should be in base and not in Circle (?).

I was collecting "preferences"-named icons. These two calendar icons are not identical. Different name, and different design (blue on the outside for preferences, grey on the outside for `calendar.svg`).

**Comment by wa4557** [comment] 2015-04-19 19:30
True. I added the calendar also to the pull-request

**Closed** 2015-04-19 19:34 UTC
Labels: enhancement
