### ISSUE TITLE
Icon for Itch

### ISSUE THREAD

**Issue by gubbug** [numixproject/numix-icon-theme-circle#3166] opened 2016-05-17 23:02 UTC
```
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=itch
TryExec=itch
Exec=itch %U
Icon=itch
Terminal=false
Categories=Game
MimeType=x-scheme-handler/itchio
Comment="Install and play itch.io games easily"
Comment[ar]="قم بتنصيب ولعب ألعاب itch.io بكل سهولة"
Comment[bg]="Инсталирайте и играйте игри от itch.io лесно"
Comment[de]="Installiere und spiele itch.io Spiele ganz bequem"
Comment[en]="Install and play itch.io games easily"
Comment[eo]="Instalu kaj ludu ludojn en itch.io facile"
Comment[es]="Instala y juega fácilmente juegos de itch.io"
Comment[fr]="Installer et jouer à des jeux itch.io facilement"
Comment[ja]="itch.ioで公開されているゲームを簡単にインストールしてお楽しみください"
Comment[nb]="Installer og spill itch.io-spill lettvint"
Comment[pl]="Łatwo instaluj i graj w gry itch.io"
Comment[pt_BR]="Instale e jogue os jogos itch.io facilmente"
Comment[pt_PT]="Instala e joga jogos do itch.io facilmente"
Comment[ro]="Instalează şi joacă jocuri de pe itch.io cu uşurinţă"
Comment[sv]="Installera och spela spel från itch.io enkelt"
Comment[zh]="简单方便的安装并开始 itch.io 游戏"
```

current icon
![](https://i.imgur.com/KFvc1jW.png)

**Comment by palob** [comment] 2016-05-18 19:35
Duplicate of #2745, we've alredy got that icon. 
@gubbug Your theme is outdated, I take it you are a PPA user?

**Comment by Foggalong** [comment] 2016-05-18 21:36
God damn, the new icon threw me off.

**Closed by Foggalong** 2016-05-18 21:36 UTC
Labels: duplicate
