### ISSUE TITLE
Icon for Telegram Desktop

### ISSUE THREAD

**Issue by mrshadowtux** [numixproject/numix-icon-theme-circle#2110] opened 2015-05-15 20:03 UTC
Please include an icon for Telegram Desktop. Would be really great to have a numix-square version of it.

![Official Icon](https://desktop.telegram.org/img/td_logo.png)

**Comment by palob** [comment] 2015-05-15 20:29
[Already done](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/telegram.svg).
Maybe it's a matter of a new icon name or a hardcoded icon path.
Could you please add the information asked for on the front page?

**Comment by Foggalong** [comment] 2015-05-16 14:45
Duplicate of #1044

**Closed by Foggalong** 2015-05-16 14:45 UTC

**Comment by Ghokun** [comment] 2015-05-16 16:30
With every telegram upgrade .desktop file changes. I always update it when telegram receives update, which is btw 1-2 update in a week.

**Comment by palob** [comment] 2015-05-16 16:42
Just copy your edited .desktop file to **~/.local/share/applications**.

It will override the global launcher and persist the updates.
