### ISSUE TITLE
Icon for CLion

### ISSUE THREAD

**Issue by btd1337** [numixproject/numix-icon-theme-circle#3105] opened 2016-05-11 03:26 UTC
Update the CLion IDE icon.

Icon=/opt/clion-2016.1.1/bin/clion.svg

![clion](https://cloud.githubusercontent.com/assets/11943860/15169165/e236df4a-170e-11e6-819f-579ac27a7d91.png)

**Comment by Foggalong** [comment] 2016-05-11 10:52
[Duplicate of these](https://github.com/numixproject/numix-icon-theme-circle/issues?q=is%3Aissue+clion+is%3Aclosed)

**Closed by Foggalong** 2016-05-11 10:52 UTC
Labels: duplicate
