### ISSUE TITLE
icon for My Weather Indicator

### ISSUE THREAD

**Issue by dfilan** [numixproject/numix-icon-theme-circle#1955] opened 2015-04-13 05:32 UTC
There is no numix circle icon for my weather indicator. Icon line says "/opt/extras.ubuntu.com/my-weather-indicator/share/pixmaps/my-weather-indicator.png". Here is an image of the original icon (sorry for poor quality): 
![screenshot from 2015-04-13 15 29 49](https://cloud.githubusercontent.com/assets/8143152/7110272/001c504c-e1f2-11e4-8071-962596099b07.png)

**Comment by dirtydancing** [comment] 2015-04-13 08:56
Hi, this is a duplicate of https://github.com/numixproject/numix-icon-theme-circle/issues/1036 and https://github.com/numixproject/numix-icon-theme-circle/issues/246, please check there for more info.

**Closed** 2015-04-13 12:29 UTC
Labels: duplicate
