### ISSUE TITLE
Manager programs of the Mint Cinnamon

### ISSUE THREAD

**Issue by ElvisPresly** [numixproject/numix-icon-theme-circle#2950] opened 2016-04-08 05:08 UTC
Icons of categories are displayed not correctly.
![virtualbox_linux mint cinnamon _08_04_2016_08_01_44](https://cloud.githubusercontent.com/assets/18265958/14374648/65e61cc6-fd69-11e5-9fea-91a400c6c30a.png)

**Comment by Foggalong** [comment] 2016-04-08 10:44
Duplicate of  #2750

**Closed by Foggalong** 2016-04-08 10:45 UTC
