### ISSUE TITLE
Icon For "Godot"

### ISSUE THREAD

**Issue by alexdmz** [numixproject/numix-icon-theme-circle#1435] opened 2015-01-08 05:12 UTC
An Numix-Square Icon Would Look And Be Awesome For This app
Icon=godot
![godot](https://cloud.githubusercontent.com/assets/8071521/5658156/3927211a-96ba-11e4-937f-87d13d6f2bdb.png)

**Comment by Foggalong** [comment] 2015-04-04 19:12
Duplicate of #1166

**Closed by Foggalong** 2015-04-04 19:13 UTC
Labels: request
