### ISSUE TITLE
No icon for Gnome Builder

### ISSUE THREAD

**Issue by handicraftsman** [numixproject/numix-icon-theme-circle#2677] opened 2015-11-15 11:59 UTC

**Comment by bil-elmoussaoui** [comment] 2015-11-15 13:15
Duplicate of #1795

**Comment by bil-elmoussaoui** [comment] 2015-11-15 13:16
Can you share paste the file content of `/usr/share/applications/org.gnome.Builder.desktop` ?

**Comment by handicraftsman** [comment] 2015-11-15 13:30
Wait

**Comment by handicraftsman** [comment] 2015-11-15 13:32
Fedora 22.
````
[Desktop Entry]
Name=Builder
Comment=Build software for GNOME
Exec=gnome-builder %U
Icon=builder
DBusActivatable=true
StartupNotify=true
Terminal=false
Type=Application
Categories=GNOME;GTK;Development;
Keywords=Build;Develop;
MimeType=text/x-c;text/x-csrc;text/x-changelog;text/x-chdr;text/x-c++hdr;text/x-python;application/x-python;application/javascript;application/x-javascript;text/x-javascript;text/javascript;text/x-js;text/x-shellscript;application/x-shellscript;text/x-sh;text/x-vala;text/x-makefile;text/x-c++;text/x-cpp;text/x-c++src;text/css;application/x-gnome-app-info;application/x-desktop;text/x-go;text/html;text/x-markdown;application/json;application/x-m4;application/xml;text/xml;application/x-yaml;text/x-sql;application/x-ruby;text/x-ruby;text/x-pkg-config;text/x-lua;text/x-php;application/x-php;text/x-php-source;application/x-php-source;text/x-perl;application/x-perl;
````

**Comment by bil-elmoussaoui** [comment] 2015-11-15 13:36
@handicraftsman you're using an old version of Numix. Please update using the git version

**Comment by handicraftsman** [comment] 2015-11-15 13:37
I'll try. Thanks.

**Comment by bil-elmoussaoui** [comment] 2015-11-15 13:38
You can close this :)

**Closed** 2015-11-15 14:17 UTC
Labels: duplicate
