### ISSUE TITLE
Icon for Gitter and Popcorn-Time

### ISSUE THREAD

**Issue by KevinCastle** [numixproject/numix-icon-theme-circle#3177] opened 2016-05-24 23:37 UTC
Gitter:
The icon line says: "/opt/Gitter/linux64/logo.png" (idk if that is what you need)
![logo](https://cloud.githubusercontent.com/assets/19513349/15523207/9c39b4ca-21e2-11e6-81d2-54f1b20c02a1.png)

Popcorn-Time:
I think it doesn't have a .desktop file because I can't find it, I had to use "Menu Creator" for make it, but well, I'm going to give you the icon btw.

![icon](https://cloud.githubusercontent.com/assets/19513349/15523216/abbaea36-21e2-11e6-94ca-0d47b8b5027c.png)

**Comment by Foggalong** [comment] 2016-05-25 09:00
Duplicate of #3177 and #413

**Closed by Foggalong** 2016-05-25 09:00 UTC
Labels: duplicate
