### ISSUE TITLE
Icon for Great Little Radio Player

### ISSUE THREAD

**Issue by pamarsan** [numixproject/numix-icon-theme-circle#1058] opened 2014-08-05 16:21 UTC
![radio1](https://cloud.githubusercontent.com/assets/7572891/3814568/8985cdfa-1cbc-11e4-9303-e0a3766d5930.png)

Icon=/opt/extras.ubuntu.com/glrp/glrp.svg

**Comment by hlechner** [comment] 2015-03-12 17:43
Adding some useful information:

**App Description**: A robust internet radio station streamer
**App Website**: https://sites.google.com/site/glrpgreatlittleradioplayer/

**App .desktop file from developer's package**:
```
[Desktop Entry]
Name=Great Little Radio Player
Comment=Robust internet radio station streamer.
Exec=/opt/extras.ubuntu.com/glrp/GreatLittleRadioPlayer
Terminal=false
Version=1.4.4
Type=Application
StartupNotify=true
Icon=/opt/extras.ubuntu.com/glrp/glrp.svg
Categories=Qt;Audio;Music;Player;AudioVideo;Video;Network;X-MandrivaLinux-Multimedia-Sound;
Name[en_US]=Great Little Radio Player
GenericName[en]=Great Little Radio Player
Comment[en]=Robust internet radio station streamer.
```

**Comment by Foggalong** [comment] 2015-04-05 17:23
Duplicate of #99

**Closed by Foggalong** 2015-04-05 17:23 UTC
Labels: hardcoded, request
