### ISSUE TITLE
Icon for xdiagnose

### ISSUE THREAD

**Issue by gitcircuit** [numixproject/numix-icon-theme-circle#2708] opened 2015-11-27 00:52 UTC
A numix-circle icon for xdiagnose is missing in Ubuntu.
Icon line say "Icon=/usr/share/xdiagnose/icons/microscope.svg" 
and the original icon is attached.

![screenshot from 2015-11-26 16-48-44](https://cloud.githubusercontent.com/assets/3539455/11432210/e1d4de3c-945d-11e5-8409-c8dda4b1d5f9.png)

**Comment by Foggalong** [comment] 2015-11-27 10:04
Duplicate of #90

**Closed by Foggalong** 2015-11-27 10:04 UTC
Labels: duplicate
