### ISSUE TITLE
Icon for xfdashboard

### ISSUE THREAD

**Issue by ricwtk** [numixproject/numix-icon-theme-circle#2168] opened 2015-05-24 11:29 UTC
The numix circle icon for xfdashboard is missing.
The icon line says "xfdashboard" and the original icon is attached.
![xfdashboard](https://cloud.githubusercontent.com/assets/3527220/7787691/90e3597a-0210-11e5-9444-b87951876b45.png)

**Comment by bil-elmoussaoui** [comment] 2015-05-24 11:44
Duplicate of this #1821 , you can download the icon from the github repo

**Closed** 2015-05-24 12:32 UTC
Labels: duplicate
