### ISSUE TITLE
goldendict icon request

### ISSUE THREAD

**Issue by raknerak** [numixproject/numix-icon-theme-circle#2415] opened 2015-07-20 13:04 UTC
goldendict is a dictionary program which can be installed from ubuntu software center. 

it has following .desktop file content:

ahmety@ahmeylnx:/usr/share/applications$ cat goldendict.desktop 
[Desktop Entry]
Type=Application
Terminal=false
Categories=Office;Dictionary;Education;Qt
Name=GoldenDict
GenericName=Multiformat Dictionary
Comment=GoldenDict
Encoding=UTF-8
Icon=/usr/share/pixmaps/goldendict.png
Exec=goldendict

Attaching goldendict.png
![goldendict](https://cloud.githubusercontent.com/assets/7880734/8776340/f28bfb04-2ef8-11e5-9d50-d3a708903398.png)

**Comment by Foggalong** [comment] 2015-07-20 15:21
Duplicate of #566

**Closed by Foggalong** 2015-07-20 15:21 UTC
